import 'package:flutter/material.dart';

/// Simple, scalable localization helper.
///
/// - Add new languages by extending `_localizedValues`.
/// - Use keys instead of hard-coded strings in widgets.
class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('hi'), Locale('mr')];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final AppLocalizations? result = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    assert(result != null, 'No AppLocalizations found in context');
    return result!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // General / common
      'app_title': 'Rozgar Adda',
      'app_logo_text': 'Rozgar',
      'sidebar_username': 'Rozgar User',
      'ok': 'OK',
      'cancel': 'Cancel',
      'continue': 'Continue',
      'back': 'Back',
      'view_all': 'View All',

      // Splash
      'splash_tagline': 'Your Gateway to Opportunities',
      'splash_launching': 'Launching your future...',
      'splash_secure_verified': 'SECURE & VERIFIED JOBS',

      // Login
      'login_title': 'Rozgar Adda',
      'login_welcome_back': 'Welcome Back',
      'login_subtitle': 'Enter your credentials to access your job portal',
      'login_email_label': 'Email Address',
      'login_email_hint': 'name@company.com',
      'login_password_label': 'Password',
      'login_forgot': 'Forgot?',
      'login_button': 'Login',
      'login_no_account': 'Don\'t have an account? ',
      'login_register': 'Register',
      'login_error_title': 'Login Failed',
      'login_error_empty': 'Please enter username and password.',

      // Registration
      'registration_progress': 'Registration Progress',
      'registration_step': 'Step 1 of 3',
      'registration_personal_info': 'Personal Info',
      'registration_full_name': 'Full Name',
      'registration_full_name_hint': 'Enter your full name',
      'registration_phone_number': 'Phone Number',
      'registration_email': 'Email Address',
      'registration_email_hint': 'name@example.com',
      'registration_address_details': 'Address Details',
      'registration_state': 'State',
      'registration_select_state': 'Select State',
      'registration_district': 'District',
      'registration_area': 'Area / Locality',
      'registration_area_hint': 'Area',
      'registration_pincode': 'Pincode',
      'registration_pincode_hint': '000000',
      'registration_full_address': 'Full Address',
      'registration_full_address_hint': 'House no, Street name...',
      'registration_identity_verification': 'Identity Verification',
      'registration_account_credentials': 'Account Credentials',
      'registration_username': 'Username',
      'registration_username_hint': 'Choose a unique username',
      'registration_password': 'Password',
      'registration_terms_prefix': 'I agree to the ',
      'registration_terms_link': 'Terms & Conditions',
      'registration_create_account': 'Create Account',
      'registration_already_account': 'Already have an account? ',
      'registration_login': 'Log In',
      'registration_join_tagline': 'Join the Workforce',
      'registration_verify_otp': 'Verify OTP',
      'registration_send_otp': 'Send OTP',
      'registration_otp_hint': 'Enter 6-digit OTP sent to your phone',
      'registration_otp_resend': 'Resend OTP',
      'registration_otp_resend_in': 'Resend in',
      'registration_otp_resend_sec': 's',
      'registration_phone_verified': '✓ Verified',
      'registration_error_otp_phone':
          'Please enter a valid 10-digit phone number.',
      'registration_error_otp_incomplete':
          'Please enter the complete 6-digit OTP.',
      'registration_otp_sent_success': 'OTP sent to your number!',
      'registration_otp_verify_success': 'Phone verified successfully!',
      'registration_error_fields': 'Please fill all required fields.',
      'registration_error_state': 'Please select a state.',
      'registration_error_district': 'Please select a district.',
      'registration_error_terms':
          'Please accept Terms and Privacy Policy to continue.',
      'registration_error_phone_verify':
          'Please verify your phone number first.',

      'registration_upload_title': 'Upload Identity Proof',
      'registration_upload_hint':
          'Aadhar Card, PAN, or Voter ID (JPG/PDF, max 2MB)',
      'registration_choose_file': 'Choose File',
      'registration_password_hint': 'Min 8 characters',
      'registration_terms_privacy': 'Privacy Policy',
      'registration_terms_and': ' and ',
      'registration_terms_suffix': ' of Rozgar Adda.',
      'select_state_appbar': 'Select State / राज्य चुनें',
      'select_state_step_label': 'STEP 2 OF 3',
      'select_state_progress': '66% Complete',
      'select_state_heading': 'Where are you looking for jobs?',
      'select_state_subheading':
          'Choose your state to see the best local opportunities tailored for you',
      'select_state_search_hint': 'Search state name...',

      // Language dialog
      'language_dialog_title': 'Select Language',
      'language_dialog_message':
          'Choose your preferred app language. You can change it anytime later.',
      'language_english': 'English',
      'language_hindi': 'Hindi',

      // Home / navigation
      'nav_home': 'HOME',
      'nav_explore': 'EXPLORE',
      'nav_saved': 'SAVED',
      'nav_profile': 'PROFILE',

      // Explore careers / job categories
      'explore_careers_title': 'Explore Careers',
      'explore_job_categories': 'Job Categories',
      'explore_job_categories_subtitle':
          'Find the perfect role across various industries',
      'explore_opportunities_pill': 'OPPORTUNITIES',
      'explore_custom_search': 'Custom Search',
      'explore_custom_search_sub': 'Find roles based on your skills',

      // Career hub / job list
      'careerhub_title': 'CareerHub',
      'careerhub_search_hint': 'Search for jobs, companies...',
      'careerhub_tab_all': 'All Jobs',
      'careerhub_tab_remote': 'Remote',
      'careerhub_tab_fulltime': 'Full-time',
      'careerhub_tab_salary': 'Salary',

      // Job detail
      'jobdetail_appbar_title': 'Job Opportunity',
      'jobdetail_annual_salary': 'ANNUAL SALARY',
      'jobdetail_experience': 'EXPERIENCE',
      'jobdetail_applicants': 'APPLICANTS',
      'jobdetail_role_description': 'Role Description',
      'jobdetail_requirements': 'Requirements',
      'jobdetail_location': 'Location',
      'jobdetail_apply_now': 'Apply Now',

      // Job application form
      'apply_header_title': 'Senior Product Designer',
      'apply_step_label': 'STEP 2 OF 4:\nEXPERIENCE',
      'apply_complete': 'Complete',
      'apply_personal_info': 'Personal Information',
      'apply_first_name': 'First Name',
      'apply_last_name': 'Last Name',
      'apply_email': 'Email Address',
      'apply_professional_details': 'Professional Details',
      'apply_current_position': 'Current Position',
      'apply_linkedin': 'LinkedIn Profile',
      'apply_resume_upload': 'Resume Upload',
      'apply_upload_cta': 'Click to upload or drag and drop',
      'apply_upload_hint': 'Max file size 10MB • PDF or DOCX',
      'apply_why_hire': 'Why should we hire you?',
      'apply_why_hire_hint':
          'Tell us briefly about your experience and why you are a great fit for this role.',
      'apply_agree':
          'I agree to share my application details with the employer.',
      'apply_submit': 'Submit Application',
      'apply_footer':
          'By submitting, you agree to our privacy policy and terms.',
      'dashboard_search_hint': 'Search for jobs, companies...',
      'dashboard_quick_links': 'Quick Links',
      'dashboard_new_job_badge': 'NEW JOB',
      'dashboard_recent_activity': 'Recent Activity',
      'dashboard_location': 'Jaipur, Rajasthan',
      'find_jobs': 'Find Jobs',
      'kyc_status': 'KYC Status',
      'sell_products': 'Sell Products',
      'marketplace': 'Marketplace',
      'earnings': 'Earnings',
      'support': 'Support',
      'news': 'News',
      'missing_persons': 'Missing Persons',
      'missing_persons_coming_soon': 'Missing Persons feature coming soon!',
      'skill_up': 'Skill Up',
      'home': 'Home',
      'products': 'Products',
      'settings': 'Settings',
      'logout': 'Logout',
      'worker_kyc_verified': 'Worker • KYC Verified',
      'menu': 'MENU',
      'registration_success_title': 'Registration Successful',
      'registration_success_message':
          'You registered successfully with this email: ',

      // Profile screen
      'profile_my_profile': 'My Profile',
      'profile_id_label': 'ID',
      'profile_edit_profile': 'Edit Profile',
      'profile_kyc_status': 'KYC Status',
      'profile_my_products': 'My Products',
      'profile_my_applications': 'My Applications',
      'profile_change_password': 'Change Password',
      'profile_help_support': 'Help & Support',
      'logout_confirm_title': 'Logout',
      'logout_confirm_message': 'Are you sure you want to logout?',

      // Splash menu
      'splash_menu_home': 'Home Screen',
      'splash_menu_about': 'About Us',
      'splash_menu_missing': 'Missing',
      'splash_menu_news': 'News',
      'splash_menu_product': 'Product',
      'splash_menu_register': 'Candidate Register',
      'splash_menu_login': 'Candidate Login',

      // Login extras
      'login_terms_agree': 'I agree to Terms of Service and Privacy Policy.',
      'login_terms_error':
          'Please accept Terms and Privacy Policy to continue.',
      'login_or_continue': 'OR CONTINUE WITH',
      'login_sign_in': 'Sign In',
      'login_error_generic': 'Something went wrong. Please try again.',

      // KYC screen
      'kyc_title': 'Edit KYC Details',
      'kyc_subtitle': 'Update your KYC information',
      'kyc_subtitle_id': 'Update your KYC information for candidate #',
      'kyc_status_pending': 'STATUS: PENDING',
      'kyc_section_personal': 'Personal Information',
      'kyc_section_address': 'Address Information',
      'kyc_section_documents': 'Documents Upload',
      'kyc_docs_hint':
          'Upload clear, readable copies. Supported: JPG, PNG, PDF, DOC',
      'kyc_field_full_name': 'Full Name',
      'kyc_field_phone': 'Phone Number',
      'kyc_field_email': 'Email Address',
      'kyc_field_state': 'State',
      'kyc_field_district': 'District',
      'kyc_field_locality': 'Locality/Area',
      'kyc_field_pincode': 'Pincode',
      'kyc_field_address': 'Complete Address',
      'kyc_address_hint': 'Flat No, Building, Street...',
      'kyc_identity_title': 'Identity Proof',
      'kyc_identity_subtitle': 'Aadhar, PAN or Passport',
      'kyc_resume_title': 'Resume / CV',
      'kyc_resume_subtitle': 'PDF or Word format',
      'kyc_photo_title': 'Profile Photo',
      'kyc_photo_subtitle': 'Recent passport size photo',
      'kyc_update_button': 'Update KYC',
      'kyc_image_source_title': 'Select Image Source',
      'kyc_source_camera': 'Camera',
      'kyc_source_gallery': 'Gallery',
      'kyc_snack_photo_uploaded': 'Photo uploaded successfully!',
      'kyc_snack_doc_uploaded': 'Document uploaded successfully!',
      'kyc_snack_file_removed': 'File removed.',
      'kyc_snack_missing_docs': 'Please upload all required documents.',
      'kyc_snack_missing_fields': 'Please fill all required fields.',
      'kyc_snack_invalid_phone': 'Please enter a valid 10-digit phone number.',
      'kyc_snack_invalid_pin': 'Please enter a valid 6-digit pincode.',
      'kyc_snack_invalid_email': 'Please enter a valid email address.',
      'kyc_snack_no_candidate': 'Candidate ID not found. Please login again.',
      'kyc_snack_updated': 'KYC updated successfully',
      'kyc_snack_failed': 'Failed to update KYC. Please try again.',
      'kyc_snack_error':
          'Something went wrong while updating KYC. Please check your connection.',
      'kyc_upload_label': 'UPLOAD',

      // News screen
      'news_title': 'Rozgar News',
      'news_trending_now': 'TRENDING NOW',
      'news_header_title': 'Career Insights for the\nModern Workforce',
      'news_read_more': 'Read More ',
      'news_mins_read': '5 MINS READ',
      'news_tab_all': 'All News',
      'news_tab_articles': 'Articles',
      'news_tab_videos': 'Videos',
      'news_error_loading': 'Failed to load news feed.',
      'news_empty_list': 'No news items available.',

      // Sell Product Screen
      'sell_post_ad': 'POST YOUR AD',
      'sell_choose_category': 'CHOOSE A CATEGORY',
      'sell_next': 'NEXT',
      'sell_category': 'CATEGORY',
      'sell_sub_category': 'SUB CATEGORY',
      'sell_details': 'DETAILS',
      'sell_no_categories': 'No categories found',
      'sell_retry': 'Retry',
      'sell_error_categories': 'Unable to load categories.',
      'sell_back': 'BACK',
      'sell_select_subcategory': 'SELECT SUB CATEGORY',
      'sell_selected_category': 'Selected Category: ',
      'sell_change_by_back': 'You can change this by going back',
      'sell_change': 'CHANGE',
      'sell_no_subcategories': 'No sub-categories found',
      'sell_subcategory_hint':
          'Choose the most relevant sub-category for your\nadvertisement to reach more buyers.',
      'sell_error_subcategories': 'Unable to load sub-categories.',
      'sell_product_title': 'Product Title',
      'sell_title_hint': 'Enter product name (e.g. BMW X5 2024)',
      'sell_description': 'Description',
      'sell_desc_hint': 'Enter detailed description...',
      'sell_features': 'Features (Separate with commas)',
      'sell_features_hint': 'Sunroof, Leather Seats, Autopilot...',
      'sell_main_image': 'Main Product Image',
      'sell_no_file': 'No file selected',
      'sell_choose_file': 'Choose File',
      'sell_gallery_images': 'Gallery Images',
      'sell_max_images': 'Max 5 images',
      'sell_price': 'Price (₹)',
      'sell_discount': 'Discount (%)',
      'sell_total_cost': 'Total Cost (₹)',
      'sell_capacity': 'Capacity',
      'sell_warranty': 'Warranty',
      'sell_active_product': 'Active Product',
      'sell_save_product': 'SAVE PRODUCT',
      'sell_select_main_image': 'Please select a main product image.',
      'sell_required': 'Required',
      'sell_error_saving': 'Something went wrong while saving the product.',
      'sell_review': 'Review',
      'sell_review_title': 'Your application is in review',
      'sell_review_desc':
          'We have received your product details. Our team will review it shortly.',
      'sell_go_dashboard': 'GO TO DASHBOARD',

      // Available Jobs
      'jobs_available_title': 'Available Jobs',
      'jobs_no_jobs_found': 'No job opportunities found for this role.',
      'jobs_loading': 'Loading job opportunities...',
      'jobs_error': 'Unable to load job opportunities.',
      'jobs_vacancy': 'Vacancy',
      'jobs_vacancies': 'Vacancies',
      'jobs_walkin': 'Walk-in',
      'jobs_apply': 'Apply',
      'jobs_salary_range': 'Salary',
      'jobs_experience': 'Experience',
      'jobs_applications': 'Applications',
      'jobs_view_details': 'View Details',
    },
    'gu': {
      // General / common
      'app_title': 'રોજગાર અડ્ડા',
      'app_logo_text': 'રોજગાર',
      'sidebar_username': 'રોજગાર યુઝર',
      'ok': 'બરાબર',
      'cancel': 'રદ કરો',
      'continue': 'ચાલુ રાખો',
      'back': 'પાછા જાઓ',
      'view_all': 'બધા જુઓ',

      // Splash
      'splash_tagline': 'તમારી તકોનું પ્રવેશદ્વાર',
      'splash_launching': 'તમારા ભવિષ્યની શરૂઆત થઈ રહી છે...',
      'splash_secure_verified': 'સુરક્ષિત અને વેરિફાઇડ નોકરીઓ',

      // Login
      'login_title': 'રોજગાર અડ્ડા',
      'login_welcome_back': 'સ્વાગત છે',
      'login_subtitle':
          'તમારા જોબ પોર્ટલનો ઉપયોગ કરવા માટે લોગિન વિગતો દાખલ કરો',
      'login_email_label': 'ઇમેઇલ સરનામું',
      'login_email_hint': 'name@company.com',
      'login_password_label': 'પાસવર્ડ',
      'login_forgot': 'ભૂલી ગયા?',
      'login_button': 'લોગિન',
      'login_no_account': 'ખાતું નથી? ',
      'login_register': 'રજીસ્ટ્રેશન કરો',
      'login_error_title': 'લોગિન નિષ્ફળ',
      'login_error_empty': 'કૃપા કરીને યુઝરનેમ અને પાસવર્ડ દાખલ કરો.',

      // Registration
      'registration_progress': 'રજીસ્ટ્રેશન પ્રગતિ',
      'registration_step': 'પગલું ૧ માંથી ૩',
      'registration_personal_info': 'વ્યક્તિગત માહિતી',
      'registration_full_name': 'પૂરું નામ',
      'registration_full_name_hint': 'તમારું પૂરું નામ દાખલ કરો',
      'registration_phone_number': 'ફોન નંબર',
      'registration_email': 'ઇમેઇલ સરનામું',
      'registration_email_hint': 'name@example.com',
      'registration_address_details': 'સરનામાની વિગતો',
      'registration_state': 'રાજ્ય',
      'registration_select_state': 'રાજ્ય પસંદ કરો',
      'registration_district': 'જિલ્લો',
      'registration_area': 'વિસ્તાર / સોસાયટી',
      'registration_area_hint': 'વિસ્તાર',
      'registration_pincode': 'પિનકોડ',
      'registration_pincode_hint': '000000',
      'registration_full_address': 'પૂરું સરનામું',
      'registration_full_address_hint': 'ઘર નંબર, શેરીનું નામ...',
      'registration_identity_verification': 'ઓળખ વેરિફિકેશન',
      'registration_account_credentials': 'ખાતાની વિગતો',
      'registration_username': 'યુઝરનેમ',
      'registration_username_hint': 'એક અજોડ યુઝરનેમ પસંદ કરો',
      'registration_password': 'પાસવર્ડ',
      'registration_terms_prefix': 'હું સંમત છું ',
      'registration_terms_link': 'નિયમો અને શરતો',
      'registration_create_account': 'ખાતું બનાવો',
      'registration_already_account': 'પહેલાથી જ ખાતું છે? ',
      'registration_login': 'લોગિન કરો',
      'registration_join_tagline': 'વર્કફોર્સમાં જોડાઓ',
      'registration_verify_otp': 'OTP વેરિફાઇ કરો',
      'registration_send_otp': 'OTP મોકલો',
      'registration_otp_hint': 'તમારા ફોન પર મોકલેલ ૬-આંકડાનો OTP દાખલ કરો',
      'registration_otp_resend': 'OTP ફરીથી મોકલો',
      'registration_otp_resend_in': 'ફરીથી મોકલો ',
      'registration_otp_resend_sec': 'સેકન્ડમાં',
      'registration_phone_verified': '✓ વેરિફાઇડ',
      'registration_error_otp_phone':
          'કૃપા કરીને માન્ય ૧૦-આંકડાનો ફોન નંબર દાખલ કરો.',
      'registration_error_otp_incomplete':
          'કૃપા કરીને સંપૂર્ણ ૬-આંકડાનો OTP દાખલ કરો.',
      'registration_otp_sent_success': 'તમારા નંબર પર OTP મોકલવામાં આવ્યો છે!',
      'registration_otp_verify_success': 'ફોન વેરિફિકેશન સફળ રહ્યું!',
      'registration_error_fields': 'કૃપા કરીને બધી ફરજિયાત વિગતો ભરો.',
      'registration_error_state': 'કૃપા કરીને રાજ્ય પસંદ કરો.',
      'registration_error_district': 'કૃપા કરીને જિલ્લો પસંદ કરો.',
      'registration_error_terms':
          'આગળ વધવા માટે કૃપા કરીને નિયમો અને ગોપનીયતા નીતિ સ્વીકારો.',
      'registration_error_phone_verify':
          'કૃપા કરીને પહેલા તમારો ફોન નંબર વેરિફાઇ કરો.',

      'registration_upload_title': 'ઓળખ પત્ર અપલોડ કરો',
      'registration_upload_hint':
          'આધાર કાર્ડ, પાન કાર્ડ, અથવા વોટર આઈડી (JPG/PDF, વધુમાં વધુ 2MB)',
      'registration_choose_file': 'ફાઇલ પસંદ કરો',
      'registration_password_hint': 'ઓછામાં ઓછા ૮ અક્ષર',
      'registration_terms_privacy': 'ગોપનીયતા નીતિ',
      'registration_terms_and': ' અને ',
      'registration_terms_suffix': ' રોજગાર અડ્ડાના.',
      'select_state_appbar': 'Select State / રાજ્ય चुनें',
      'select_state_step_label': 'પગલું ૨ માંથી ૩',
      'select_state_progress': '૬૬% પૂર્ણ',
      'select_state_heading': 'તમે ક્યાં નોકરી શોધી રહ્યા છો?',
      'select_state_subheading':
          'તમારા માટે ખાસ તૈયાર કરાયેલી શ્રેષ્ઠ સ્થાનિક તકો જોવા માટે તમારું રાજ્ય પસંદ કરો',
      'select_state_search_hint': 'રાજ્યનું નામ શોધો...',

      // Language dialog
      'language_dialog_title': 'ભાષા પસંદ કરો',
      'language_dialog_message':
          'તમારી પસંદગીની એપ્લિકેશન ભાષા પસંદ કરો. તમે તેને પછીથી ગમે ત્યારે બદલી શકો છો.',
      'language_english': 'English',
      'language_hindi': 'Hindi',

      // Home / navigation
      'nav_home': 'હોમ',
      'nav_explore': 'એક્સપ્લોર',
      'nav_saved': 'સેવ કરેલું',
      'nav_profile': 'પ્રોફાઇલ',

      // Explore careers / job categories
      'explore_careers_title': 'કરિયર એક્સપ્લોર કરો',
      'explore_job_categories': 'નોકરીની શ્રેણીઓ',
      'explore_job_categories_subtitle':
          'વિવિધ ઉદ્યોગોમાં તમારા માટે યોગ્ય ભૂમિકા શોધો',
      'explore_opportunities_pill': 'તકો',
      'explore_custom_search': 'કસ્ટમ સર્ચ',
      'explore_custom_search_sub': 'તમારા કૌશલ્યોના આધારે નોકરીઓ શોધો',

      // Career hub / job list
      'careerhub_title': 'કરિયરહબ',
      'careerhub_search_hint': 'નોકરીઓ, કંપનીઓ શોધો...',
      'careerhub_tab_all': 'બધી નોકરીઓ',
      'careerhub_tab_remote': 'રિમોટ (ઘરેથી)',
      'careerhub_tab_fulltime': 'ફૂલ-ટાઇમ',
      'careerhub_tab_salary': 'પગાર',

      // Job detail
      'jobdetail_appbar_title': 'નોકરીની તક',
      'jobdetail_annual_salary': 'વાર્ષિક પગાર',
      'jobdetail_experience': 'અનુભવ',
      'jobdetail_applicants': 'અરજદારો',
      'jobdetail_role_description': 'કામનું વર્ણન',
      'jobdetail_requirements': 'જરૂરિયાતો',
      'jobdetail_location': 'સ્થળ',
      'jobdetail_apply_now': 'હમણાં અરજી કરો',

      // Job application form
      'apply_header_title': 'સિનિયર પ્રોડક્ટ ડિઝાઇનર',
      'apply_step_label': 'પગલું ૨ માંથી ૪:\nઅનુભવ',
      'apply_complete': 'પૂર્ણ',
      'apply_personal_info': 'વ્યક્તિગત માહિતી',
      'apply_first_name': 'પ્રથમ નામ',
      'apply_last_name': 'અટક / છેલ્લું નામ',
      'apply_email': 'ઇમેઇલ સરનામું',
      'apply_professional_details': 'વ્યવસાયિક વિગતો',
      'apply_current_position': 'વર્તમાન હોદ્દો',
      'apply_linkedin': 'લિંક્ડઇન પ્રોફાઇલ',
      'apply_resume_upload': 'રેઝ્યૂમે અપલોડ',
      'apply_upload_cta':
          'અપલોડ કરવા માટે ક્લિક કરો અથવા ફાઇલ ખેંચીને અહીં લાવો',
      'apply_upload_hint': 'વધુમાં વધુ ફાઇલ સાઈઝ 10MB • PDF અથવા DOCX',
      'apply_why_hire': 'અમે તમને કેમ નોકરી પર રાખીએ?',
      'apply_why_hire_hint':
          'તમારા અનુભવ વિશે ટૂંકમાં જણાવો અને તમે આ ભૂમિકા માટે કેમ યોગ્ય છો તે લખો.',
      'apply_agree':
          'હું એમ્પ્લોયર (માલિક) સાથે મારી અરજીની વિગતો શેર કરવા માટે સંમત છું.',
      'apply_submit': 'અરજી સબમિટ કરો',
      'apply_footer':
          'સબમિટ કરીને, તમે અમારી ગોપનીયતા નીતિ અને શરતો સાથે સંમત થાઓ છો.',
      'dashboard_search_hint': 'નોકરીઓ, કંપનીઓ શોધો...',
      'dashboard_quick_links': 'ઝડપી લિંક્સ',
      'dashboard_new_job_badge': 'નવી નોકરી',
      'dashboard_recent_activity': 'તાજેતરની પ્રવૃત્તિ',
      'dashboard_location': 'જયપુર, રાજસ્થાન',
      'find_jobs': 'નોકરીઓ શોધો',
      'kyc_status': 'KYC સ્ટેટસ',
      'sell_products': 'પ્રોડક્ટ્સ વેચો',
      'marketplace': 'માર્કેટપ્લેસ',
      'earnings': 'કમણી',
      'support': 'સપોર્ટ',
      'news': 'સમાચાર',
      'missing_persons': 'ગુમ થયેલ વ્યક્તિઓ',
      'missing_persons_coming_soon':
          'ગુમ થયેલ વ્યક્તિઓનું ફીચર ટૂંક સમયમાં આવી રહ્યું છે!',
      'skill_up': 'કૌશલ્ય વધારો',
      'home': 'હોમ',
      'products': 'પ્રોડક્ટ્સ',
      'settings': 'સેટિંગ્સ',
      'logout': 'લોગઆઉટ',
      'worker_kyc_verified': 'કામદાર • KYC વેરિફાઇડ',
      'menu': 'મેનૂ',
      'registration_success_title': 'રજીસ્ટ્રેશન સફળ રહ્યું',
      'registration_success_message':
          'તમે આ ઇમેઇલ સાથે સફળતાપૂર્વક રજીસ્ટ્રેશન કર્યું છે: ',

      // Profile screen
      'profile_my_profile': 'મારી પ્રોફાઇલ',
      'profile_id_label': 'ID',
      'profile_edit_profile': 'પ્રોફાઇલ એડિટ કરો',
      'profile_kyc_status': 'KYC સ્ટેટસ',
      'profile_my_products': 'મારી પ્રોડક્ટ્સ',
      'profile_my_applications': 'મારી અરજીઓ',
      'profile_change_password': 'પાસવર્ડ બદલો',
      'profile_help_support': 'મદદ અને સપોર્ટ',
      'logout_confirm_title': 'લોગઆઉટ',
      'logout_confirm_message': 'શું તમે ખરેખર લોગઆઉટ કરવા માંગો છો?',

      // Splash menu
      'splash_menu_home': 'હોમ સ્ક્રીન',
      'splash_menu_about': 'અમારા વિશે',
      'splash_menu_missing': 'ગુમ થયેલ',
      'splash_menu_news': 'સમાચાર',
      'splash_menu_product': 'પ્રોડક્ટ',
      'splash_menu_register': 'ઉમેદવાર રજીસ્ટ્રેશન',
      'splash_menu_login': 'ઉમેદવાર લોગિન',

      // Login extras
      'login_terms_agree': 'હું સેવાની શરતો અને ગોપનીયતા નીતિ સાથે સંમત છું.',
      'login_terms_error':
          'આગળ વધવા માટે કૃપા કરીને નિયમો અને ગોપનીયતા નીતિ સ્વીકારો.',
      'login_or_continue': 'અથવા આના દ્વારા ચાલુ રાખો',
      'login_sign_in': 'સાઇન ઇન કરો',
      'login_error_generic': 'કંઈક ખોટું થયું. કૃપા કરીને ફરી પ્રયાસ કરો.',

      // KYC screen
      'kyc_title': 'KYC વિગતો સુધારો',
      'kyc_subtitle': 'તમારી KYC માહિતી અપડેટ કરો',
      'kyc_subtitle_id': 'ઉમેદવાર # માટે તમારી KYC માહિતી અપડેટ કરો',
      'kyc_status_pending': 'સ્ટેટસ: પેન્ડિંગ (બાકી)',
      'kyc_section_personal': 'વ્યક્તિગત માહિતી',
      'kyc_section_address': 'સરનામાની માહિતી',
      'kyc_section_documents': 'દસ્તાવેજો અપલોડ કરો',
      'kyc_docs_hint':
          'સ્પષ્ટ અને વાંચી શકાય તેવી નકલો અપલોડ કરો. સપોર્ટેડ: JPG, PNG, PDF, DOC',
      'kyc_field_full_name': 'પૂરું નામ',
      'kyc_field_phone': 'ફોન નંબર',
      'kyc_field_email': 'ઇમેઇલ સરનામું',
      'kyc_field_state': 'રાજ્ય',
      'kyc_field_district': 'જિલ્લો',
      'kyc_field_locality': 'વિસ્તાર/સોસાયટી',
      'kyc_field_pincode': 'પિનકોડ',
      'kyc_field_address': 'સંપૂર્ણ સરનામું',
      'kyc_address_hint': 'ફ્લેટ નંબર, બિલ્ડિંગ, શેરી...',
      'kyc_identity_title': 'ઓળખ પત્ર',
      'kyc_identity_subtitle': 'આધાર, પાન અથવા પાસપોર્ટ',
      'kyc_resume_title': 'રેઝ્યૂમે / CV',
      'kyc_resume_subtitle': 'PDF અથવા Word ફોર્મેટ',
      'kyc_photo_title': 'પ્રોફાઇલ ફોટો',
      'kyc_photo_subtitle': 'તાજેતરનો પાસપોર્ટ સાઇઝનો ફોટો',
      'kyc_update_button': 'KYC અપડેટ કરો',
      'kyc_image_source_title': 'ફોટો મેળવવાનું સ્થાન પસંદ કરો',
      'kyc_source_camera': 'કેમેરા',
      'kyc_source_gallery': 'ગેલેરી',
      'kyc_snack_photo_uploaded': 'ફોટો સફળતાપૂર્વક અપલોડ થયો!',
      'kyc_snack_doc_uploaded': 'દસ્તાવેજ સફળતાપૂર્વક અપલોડ થયો!',
      'kyc_snack_file_removed': 'ફાઇલ હટાવવામાં આવી.',
      'kyc_snack_missing_docs': 'કૃપા કરીને બધા જરૂરી દસ્તાવેજો અપલોડ કરો.',
      'kyc_snack_missing_fields': 'કૃપા કરીને બધી ફરજિયાત વિગતો ભરો.',
      'kyc_snack_invalid_phone':
          'કૃપા કરીને માન્ય ૧૦-આંકડાનો ફોન નંબર દાખલ કરો.',
      'kyc_snack_invalid_pin': 'કૃપા કરીને માન્ય ૬-આંકડાનો પિનકોડ દાખલ કરો.',
      'kyc_snack_invalid_email': 'કૃપા કરીને માન્ય ઇમેઇલ સરનામું દાખલ કરો.',
      'kyc_snack_no_candidate':
          'ઉમેદવાર ID મળ્યો નથી. કૃપા કરીને ફરી લોગિન કરો.',
      'kyc_snack_updated': 'KYC સફળતાપૂર્વક અપડેટ થયું',
      'kyc_snack_failed':
          'KYC અપડેટ કરવામાં નિષ્ફળતા. કૃપા કરીને ફરી પ્રયાસ કરો.',
      'kyc_snack_error':
          'KYC અપડેટ કરતી વખતે કંઈક ખોટું થયું. કૃપા કરીને તમારું કનેક્શન તપાસો.',
      'kyc_upload_label': 'અપલોડ કરો',

      // News screen
      'news_title': 'રોજગાર સમાચાર',
      'news_trending_now': 'ટ્રેન્ડિંગ સમાચાર',
      'news_header_title': 'આધુનિક વર્કફોર્સ માટે\nકરિયર માર્ગદર્શન',
      'news_read_more': 'વધુ વાંચો ',
      'news_mins_read': '૫ મિનિટ વાંચન',
      'news_tab_all': 'બધા સમાચાર',
      'news_tab_articles': 'લેખો',
      'news_tab_videos': 'વીડિયો',
      'news_error_loading': 'સમાચાર લોડ કરવામાં નિષ્ફળતા.',
      'news_empty_list': 'કોઈ સમાચાર ઉપલબ્ધ નથી.',

      // Sell Product Screen
      'sell_post_ad': 'તમારી જાહેરાત મૂકો',
      'sell_choose_category': 'શ્રેણી પસંદ કરો',
      'sell_next': 'આગળ',
      'sell_category': 'શ્રેણી',
      'sell_sub_category': 'ઉપ-શ્રેણી',
      'sell_details': 'વિગતો',
      'sell_no_categories': 'કોઈ શ્રેણીઓ મળી નથી',
      'sell_retry': 'ફરી પ્રયાસ કરો',
      'sell_error_categories': 'શ્રેણીઓ લોડ કરવામાં અસમર્થ.',
      'sell_back': 'પાછા જાઓ',
      'sell_select_subcategory': 'ઉપ-શ્રેણી પસંદ કરો',
      'sell_selected_category': 'પસંદ કરેલ શ્રેણી: ',
      'sell_change_by_back': 'તમે પાછા જઈને આ બદલી શકો છો',
      'sell_change': 'બદલો',
      'sell_no_subcategories': 'કોઈ ઉપ-શ્રેણીઓ મળી નથી',
      'sell_subcategory_hint':
          'વધુ ખરીદદારો સુધી પહોંચવા માટે તમારી જાહેરાત માટે સૌથી સંબંધિત ઉપ-શ્રેણી પસંદ કરો.',
      'sell_error_subcategories': 'ઉપ-શ્રેણીઓ લોડ કરવામાં અસમર્થ.',
      'sell_product_title': 'પ્રોડક્ટનું શીર્ષક',
      'sell_title_hint': 'પ્રોડક્ટનું નામ દાખલ કરો (દા.ત. BMW X5 2024)',
      'sell_description': 'વર્ણન',
      'sell_desc_hint': 'વિગતવાર વર્ણન દાખલ કરો...',
      'sell_features': 'વિશેષતાઓ (અલ્પવિરામથી અલગ કરો)',
      'sell_features_hint': 'સનરૂફ, લેધર સીટ્સ, ઓટોપાયલટ...',
      'sell_main_image': 'પ્રોડક્ટનો મુખ્ય ફોટો',
      'sell_no_file': 'કોઈ ફાઇલ પસંદ કરી નથી',
      'sell_choose_file': 'ફાઇલ પસંદ કરો',
      'sell_gallery_images': 'ગેલેરીના ફોટા',
      'sell_max_images': 'વધુમાં વધુ ૫ ફોટા',
      'sell_price': 'કિંમત (₹)',
      'sell_discount': 'ડિસ્કાઉન્ટ (%)',
      'sell_total_cost': 'કુલ કિંમત (₹)',
      'sell_capacity': 'ક્ષમતા',
      'sell_warranty': 'વોરંટી',
      'sell_active_product': 'સક્રિય પ્રોડક્ટ',
      'sell_save_product': 'પ્રોડક્ટ સેવ કરો',
      'sell_select_main_image': 'કૃપા કરીને પ્રોડક્ટનો મુખ્ય ફોટો પસંદ કરો.',
      'sell_required': 'જરૂરી',
      'sell_error_saving': 'પ્રોડક્ટ સેવ કરતી વખતે કંઈક ખોટું થયું.',
      'sell_review': 'રિવ્યૂ હેઠળ',
      'sell_review_title': 'તમારી અરજી રિવ્યૂ હેઠળ છે',
      'sell_review_desc':
          'અમને તમારી પ્રોડક્ટની વિગતો મળી ગઈ છે. અમારી ટીમ ટૂંક સમયમાં તેની સમીક્ષા કરશે.',
      'sell_go_dashboard': 'ડૅશબોર્ડ પર જાઓ',

      // Available Jobs
      'jobs_available_title': 'ઉપલબ્ધ નોકરીઓ',
      'jobs_no_jobs_found': 'આ ભૂમિકા માટે કોઈ નોકરીની તકો મળી નથી.',
      'jobs_loading': 'નોકરીની તકો લોડ થઈ રહી છે...',
      'jobs_error': 'નોકરીની તકો લોડ કરવામાં અસમર્થ.',
      'jobs_vacancy': 'જગ્યા',
      'jobs_vacancies': 'જગ્યાઓ',
      'jobs_walkin': 'વોક-ઈન',
      'jobs_apply': 'અરજી કરો',
      'jobs_salary_range': 'પગાર',
      'jobs_experience': 'અનુભવ',
      'jobs_applications': 'અરજીઓ',
      'jobs_view_details': 'વિગતો જુઓ',
    },
    'ta': {
      // General / common
      'app_title': 'ரோஸ்கார் அட்டா',
      'app_logo_text': 'ரோஸ்கார்',
      'sidebar_username': 'ரோஸ்கார் பயனர்',
      'ok': 'சரி',
      'cancel': 'ரத்துசெய்',
      'continue': 'தொடரவும்',
      'back': 'பின்னே செல்',
      'view_all': 'அனைத்தையும் பார்',

      // Splash
      'splash_tagline': 'வாய்ப்புகளுக்கான உங்கள் நுழைவாயில்',
      'splash_launching': 'உங்கள் எதிர்காலத்தை நோக்கிய பயணம்...',
      'splash_secure_verified': 'பாதுகாப்பான மற்றும் சரிபார்க்கப்பட்ட வேலைகள்',

      // Login
      'login_title': 'ரோஸ்கார் அட்டா',
      'login_welcome_back': 'நல்வரவு',
      'login_subtitle':
          'உங்கள் வேலை வாய்ப்பு போர்ட்டலை அணுக உங்கள் விபரங்களை உள்ளிடவும்',
      'login_email_label': 'மின்னஞ்சல் முகவரி',
      'login_email_hint': 'name@company.com',
      'login_password_label': 'கடவுச்சொல்',
      'login_forgot': 'மறந்துவிட்டதா?',
      'login_button': 'உள்நுழை',
      'login_no_account': 'கணக்கு இல்லையா? ',
      'login_register': 'பதிவு செய்',
      'login_error_title': 'உள்நுழைவு தோல்வியடைந்தது',
      'login_error_empty': 'பயனர் பெயர் மற்றும் கடவுச்சொல்லை உள்ளிடவும்.',

      // Registration
      'registration_progress': 'பதிவு முன்னேற்றம்',
      'registration_step': 'படி 3 இல் 1',
      'registration_personal_info': 'தனிப்பட்ட தகவல்',
      'registration_full_name': 'முழு பெயர்',
      'registration_full_name_hint': 'உங்கள் முழு பெயரை உள்ளிடவும்',
      'registration_phone_number': 'தொலைபேசி எண்',
      'registration_email': 'மின்னஞ்சல் முகவரி',
      'registration_email_hint': 'name@example.com',
      'registration_address_details': 'முகவரி விவரங்கள்',
      'registration_state': 'மாநிலம்',
      'registration_select_state': 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
      'registration_district': 'மாவட்டம்',
      'registration_area': 'பகுதி / இருப்பிடம்',
      'registration_area_hint': 'பகுதி',
      'registration_pincode': 'அஞ்சல் குறியீடு (Pincode)',
      'registration_pincode_hint': '000000',
      'registration_full_address': 'முழு முகவரி',
      'registration_full_address_hint': 'கதவு எண், தெரு பெயர்...',
      'registration_identity_verification': 'அடையாளச் சரிபார்ப்பு',
      'registration_account_credentials': 'கணக்கு விபரங்கள்',
      'registration_username': 'பயனர் பெயர்',
      'registration_username_hint':
          'தனித்துவமான பயனர் பெயரைத் தேர்ந்தெடுக்கவும்',
      'registration_password': 'கடவுச்சொல்',
      'registration_terms_prefix': 'நான் ஏற்றுக்கொள்கிறேன் ',
      'registration_terms_link': 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
      'registration_create_account': 'கணக்கை உருவாக்கு',
      'registration_already_account': 'ஏற்கனவே கணக்கு உள்ளதா? ',
      'registration_login': 'உள்நுழைக',
      'registration_join_tagline': 'பணியாளராக இணையுங்கள்',
      'registration_verify_otp': 'OTP-ஐச் சரிபார்',
      'registration_send_otp': 'OTP அனுப்பு',
      'registration_otp_hint':
          'உங்கள் தொலைபேசிக்கு அனுப்பப்பட்ட 6 இலக்க OTP-ஐ உள்ளிடவும்',
      'registration_otp_resend': 'OTP-ஐ மீண்டும் அனுப்பு',
      'registration_otp_resend_in': 'மீண்டும் அனுப்ப ',
      'registration_otp_resend_sec': 'விநாடிகள்',
      'registration_phone_verified': '✓ சரிபார்க்கப்பட்டது',
      'registration_error_otp_phone':
          'முறையான 10 இலக்க தொலைபேசி எண்ணை உள்ளிடவும்.',
      'registration_error_otp_incomplete':
          'முழுமையான 6 இலக்க OTP-ஐ உள்ளிடவும்.',
      'registration_otp_sent_success': 'உங்கள் எண்ணிற்கு OTP அனுப்பப்பட்டது!',
      'registration_otp_verify_success':
          'தொலைபேசி எண் வெற்றிகரமாக சரிபார்க்கப்பட்டது!',
      'registration_error_fields': 'தேவையான அனைத்து விவரங்களையும் நிரப்பவும்.',
      'registration_error_state':
          'தயவுசெய்து ஒரு மாநிலத்தைத் தேர்ந்தெடுக்கவும்.',
      'registration_error_district':
          'தயவுசெய்து ஒரு மாவட்டத்தைத் தேர்ந்தெடுக்கவும்.',
      'registration_error_terms':
          'தொடர, விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஏற்கவும்.',
      'registration_error_phone_verify':
          'முதலில் உங்கள் தொலைபேசி எண்ணைச் சரிபார்க்கவும்.',

      'registration_upload_title': 'அடையாளச் சான்றை பதிவேற்றவும்',
      'registration_upload_hint':
          'ஆதார் கார்டு, பான் கார்டு அல்லது வாக்காளர் அடையாள அட்டை (JPG/PDF, அதிகபட்சம் 2MB)',
      'registration_choose_file': 'கோப்பைத் தேர்ந்தெடு',
      'registration_password_hint': 'குறைந்தது 8 எழுத்துக்கள்',
      'registration_terms_privacy': 'தனியுரிமைக் கொள்கை',
      'registration_terms_and': ' மற்றும் ',
      'registration_terms_suffix': ' ரோஸ்கார் அட்டா இன் விதிமுறைகள்.',
      'select_state_appbar': 'Select State / மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
      'select_state_step_label': 'படி 3 இல் 2',
      'select_state_progress': '66% நிறைவடைந்தது',
      'select_state_heading': 'நீங்கள் எங்கு வேலை தேடுகிறீர்கள்?',
      'select_state_subheading':
          'உங்களுக்கு ஏற்ற சிறந்த உள்ளூர் வேலை வாய்ப்புகளைப் பார்க்க உங்கள் மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
      'select_state_search_hint': 'மாநிலப் பெயரைத் தேடவும்...',

      // Language dialog
      'language_dialog_title': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'language_dialog_message':
          'உங்களுக்கு விருப்பமான பயன்பாட்டு மொழியைத் தேர்ந்தெடுக்கவும். இதை நீங்கள் எப்போது வேண்டுமானாலும் மாற்றிக்கொள்ளலாம்.',
      'language_english': 'English',
      'language_hindi': 'Hindi',

      // Home / navigation
      'nav_home': 'முகப்பு',
      'nav_explore': 'ஆராய்வு',
      'nav_saved': 'சேமித்தவை',
      'nav_profile': 'சுயவிவரம்',

      // Explore careers / job categories
      'explore_careers_title': 'தொழில்துறைகளை ஆராயுங்கள்',
      'explore_job_categories': 'வேலை பிரிவுகள்',
      'explore_job_categories_subtitle':
          'பல்வேறு துறைகளில் உங்களுக்கான சரியான பணியைத் கண்டறியவும்',
      'explore_opportunities_pill': 'வாய்ப்புகள்',
      'explore_custom_search': 'விருப்பத் தேடல்',
      'explore_custom_search_sub':
          'உங்கள் திறன்களின் அடிப்படையில் பணிகளைக் கண்டறியவும்',

      // Career hub / job list
      'careerhub_title': 'கரியர்ஹப்',
      'careerhub_search_hint': 'வேலைகள், நிறுவனங்களைத் தேடவும்...',
      'careerhub_tab_all': 'அனைத்து வேலைகள்',
      'careerhub_tab_remote': 'தொலைதூர வேலை (Remote)',
      'careerhub_tab_fulltime': 'முழு நேர வேலை',
      'careerhub_tab_salary': 'சம்பளம்',

      // Job detail
      'jobdetail_appbar_title': 'வேலை வாய்ப்பு',
      'jobdetail_annual_salary': 'ஆண்டு சம்பளம்',
      'jobdetail_experience': 'அனுபவம்',
      'jobdetail_applicants': 'விண்ணப்பித்தவர்கள்',
      'jobdetail_role_description': 'பணி விளக்கம்',
      'jobdetail_requirements': 'தகுதிகள் / தேவைகள்',
      'jobdetail_location': 'இடம்',
      'jobdetail_apply_now': 'இப்போதே விண்ணப்பி',

      // Job application form
      'apply_header_title':
          'சீனியர் தயாரிப்பு வடிவமைப்பாளர் (Product Designer)',
      'apply_step_label': 'படி 4 இல் 2:\nஅனுபவம்',
      'apply_complete': 'முடிந்தது',
      'apply_personal_info': 'தனிப்பட்ட தகவல்கள்',
      'apply_first_name': 'முதல் பெயர்',
      'apply_last_name': 'குடும்பப் பெயர் / கடைசி பெயர்',
      'apply_email': 'மின்னஞ்சல் முகவரி',
      'apply_professional_details': 'தொழில்முறை விவரங்கள்',
      'apply_current_position': 'தற்போதைய பதவி',
      'apply_linkedin': 'LinkedIn சுயவிவரம்',
      'apply_resume_upload': 'சுயவிவரக் குறிப்பு (Resume) பதிவேற்றம்',
      'apply_upload_cta':
          'பதிவேற்ற கிளிக் செய்யவும் அல்லது கோப்பை இழுத்து வந்து போடவும்',
      'apply_upload_hint': 'அதிகபட்ச கோப்பு அளவு 10MB • PDF அல்லது DOCX',
      'apply_why_hire': 'நாங்கள் ஏன் உங்களை வேலைக்கு அமர்த்த வேண்டும்?',
      'apply_why_hire_hint':
          'உங்கள் அனுபவத்தைப் பற்றியும், இந்த வேலைக்கு நீங்கள் எவ்வாறு பொருத்தமானவர் என்றும் சுருக்கமாகக் கூறவும்.',
      'apply_agree':
          'எனது விண்ணப்ப விவரங்களை முதலாளியுடன் பகிர்ந்து கொள்ள ஒப்புக்கொள்கிறேன்.',
      'apply_submit': 'விண்ணப்பத்தைச் சமர்ப்பி',
      'apply_footer':
          'சமர்ப்பிப்பதன் மூலம், எங்கள் தனியுரிமைக் கொள்கை மற்றும் விதிமுறைகளை நீங்கள் ஒப்புக்கொள்கிறீர்கள்.',
      'dashboard_search_hint': 'வேலைகள், நிறுவனங்களைத் தேடவும்...',
      'dashboard_quick_links': 'விரைவு இணைப்புகள்',
      'dashboard_new_job_badge': 'புதிய வேலை',
      'dashboard_recent_activity': 'சமீபத்திய செயல்பாடு',
      'dashboard_location': 'ஜெய்ப்பூர், ராஜஸ்தான்',
      'find_jobs': 'வேலைகளைத் தேடு',
      'kyc_status': 'KYC நிலை',
      'sell_products': 'பொருட்களை விற்பனை செய்',
      'marketplace': 'சந்தை (Marketplace)',
      'earnings': 'வருவாய்',
      'support': 'ஆதரவு / உதவி',
      'news': 'செய்திகள்',
      'missing_persons': 'காணாமல் போனவர்கள்',
      'missing_persons_coming_soon': 'காணாமல் போனவர்கள் அம்சம் விரைவில் வரும்!',
      'skill_up': 'திறனை மேம்படுத்து',
      'home': 'முகப்பு',
      'products': 'பொருட்கள்',
      'settings': 'அமைப்புகள்',
      'logout': 'வெளியேறு',
      'worker_kyc_verified': 'தொழிலாளி • KYC சரிபார்க்கப்பட்டது',
      'menu': 'பட்டி (MENU)',
      'registration_success_title': 'பதிவு வெற்றிகரமாக முடிந்தது',
      'registration_success_message':
          'இந்த மின்னஞ்சல் முகவரியுடன் வெற்றிகரமாகப் பதிவு செய்துள்ளீர்கள்: ',

      // Profile screen
      'profile_my_profile': 'எனது சுயவிவரம்',
      'profile_id_label': 'ID',
      'profile_edit_profile': 'சுயவிவரத்தைத் திருத்து',
      'profile_kyc_status': 'KYC நிலை',
      'profile_my_products': 'எனது பொருட்கள்',
      'profile_my_applications': 'எனது விண்ணப்பங்கள்',
      'profile_change_password': 'கடவுச்சொல்லை மாற்று',
      'profile_help_support': 'உதவி மற்றும் ஆதரவு',
      'logout_confirm_title': 'வெளியேறு',
      'logout_confirm_message': 'நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',

      // Splash menu
      'splash_menu_home': 'முகப்புத் திரை',
      'splash_menu_about': 'எங்களைப் பற்றி',
      'splash_menu_missing': 'காணாமல் போனவை',
      'splash_menu_news': 'செய்திகள்',
      'splash_menu_product': 'தயாரிப்பு',
      'splash_menu_register': 'வேட்பாளர் பதிவு',
      'splash_menu_login': 'வேட்பாளர் உள்நுழைவு',

      // Login extras
      'login_terms_agree':
          'சேவை விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை நான் ஒப்புக்கொள்கிறேன்.',
      'login_terms_error':
          'தொடர, விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஏற்கவும்.',
      'login_or_continue': 'அல்லது இதனுடன் தொடரவும்',
      'login_sign_in': 'உள்நுழைக',
      'login_error_generic': 'ஏதோ தவறு நடந்துவிட்டது. மீண்டும் முயற்சிக்கவும்.',

      // KYC screen
      'kyc_title': 'KYC விபரங்களைத் திருத்து',
      'kyc_subtitle': 'உங்கள் KYC தகவலைப் புதுப்பிக்கவும்',
      'kyc_subtitle_id': 'வேட்பாளர் # க்கான உங்கள் KYC தகவலைப் புதுப்பிக்கவும்',
      'kyc_status_pending': 'நிலை: நிலுவையில் உள்ளது (PENDING)',
      'kyc_section_personal': 'தனிப்பட்ட தகவல்கள்',
      'kyc_section_address': 'முகவரி விபரங்கள்',
      'kyc_section_documents': 'ஆவணங்கள் பதிவேற்றம்',
      'kyc_docs_hint':
          'தெளிவான, படிக்கக்கூடிய பிரதிகளைப் பதிவேற்றவும். அனுமதிக்கப்படுபவை: JPG, PNG, PDF, DOC',
      'kyc_field_full_name': 'முழு பெயர்',
      'kyc_field_phone': 'தொலைபேசி எண்',
      'kyc_field_email': 'மின்னஞ்சல் முகவரி',
      'kyc_field_state': 'மாநிலம்',
      'kyc_field_district': 'மாவட்டம்',
      'kyc_field_locality': 'பகுதி/இருப்பிடம்',
      'kyc_field_pincode': 'அஞ்சல் குறியீடு (Pincode)',
      'kyc_field_address': 'முழுமையான முகவரி',
      'kyc_address_hint': 'பிளாட் எண், கட்டிடம், தெரு...',
      'kyc_identity_title': 'அடையாளச் சான்று',
      'kyc_identity_subtitle': 'ஆதார், பான் அல்லது பாஸ்போர்ட்',
      'kyc_resume_title': 'சுயவிவரக் குறிப்பு / CV',
      'kyc_resume_subtitle': 'PDF அல்லது Word வடிவம்',
      'kyc_photo_title': 'சுயவிவரப் புகைப்படம்',
      'kyc_photo_subtitle': 'சமீபத்திய பாஸ்போர்ட் அளவு புகைப்படம்',
      'kyc_update_button': 'KYC-ஐப் புதுப்பி',
      'kyc_image_source_title': 'புகைப்பட மூலத்தைத் தேர்ந்தெடுக்கவும்',
      'kyc_source_camera': 'கேமரா',
      'kyc_source_gallery': 'கேலரி',
      'kyc_snack_photo_uploaded': 'புகைப்படம் வெற்றிகரமாக பதிவேற்றப்பட்டது!',
      'kyc_snack_doc_uploaded': 'ஆவணம் வெற்றிகரமாக பதிவேற்றப்பட்டது!',
      'kyc_snack_file_removed': 'கோப்பு அகற்றப்பட்டது.',
      'kyc_snack_missing_docs': 'தேவையான அனைத்து ஆவணங்களையும் பதிவேற்றவும்.',
      'kyc_snack_missing_fields': 'தேவையான அனைத்து விவரங்களையும் நிரப்பவும்.',
      'kyc_snack_invalid_phone': 'முறையான 10 இலக்க தொலைபேசி எண்ணை உள்ளிடவும்.',
      'kyc_snack_invalid_pin':
          'முறையான 6 இலக்க அஞ்சல் குறியீட்டை (Pincode) உள்ளிடவும்.',
      'kyc_snack_invalid_email': 'முறையான மின்னஞ்சல் முகவரியை உள்ளிடவும்.',
      'kyc_snack_no_candidate':
          'வேட்பாளர் ID கண்டறியப்படவில்லை. மீண்டும் உள்நுழையவும்.',
      'kyc_snack_updated': 'KYC வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
      'kyc_snack_failed':
          'KYC-ஐப் புதுப்பிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
      'kyc_snack_error':
          'KYC-ஐப் புதுப்பிக்கும்போது ஏதோ தவறு நடந்தது. உங்கள் இணைய இணைப்பைச் சரிபார்க்கவும்.',
      'kyc_upload_label': 'பதிவேற்று',

      // News screen
      'news_title': 'ரோஸ்கார் செய்திகள்',
      'news_trending_now': 'தற்போது பிரபலமாக உள்ளவை',
      'news_header_title': 'நவீன பணியாளர்களுக்கான\nதொழில் வழிகாட்டுதல்கள்',
      'news_read_more': 'மேலும் படிக்க ',
      'news_mins_read': '5 நிமிட வாசிப்பு',
      'news_tab_all': 'அனைத்து செய்திகள்',
      'news_tab_articles': 'கட்டுரைகள்',
      'news_tab_videos': 'காணொளிகள்',
      'news_error_loading': 'செய்திகளை ஏற்றுவதில் தோல்வி.',
      'news_empty_list': 'செய்திகள் எதுவும் கிடைக்கவில்லை.',

      // Sell Product Screen
      'sell_post_ad': 'உங்கள் விளம்பரத்தைப் பதிவிடவும்',
      'sell_choose_category': 'ஒரு பிரிவைத் தேர்ந்தெடுக்கவும்',
      'sell_next': 'அடுத்து',
      'sell_category': 'பிரிவு (Category)',
      'sell_sub_category': 'துணைப் பிரிவு (Sub Category)',
      'sell_details': 'விவரங்கள்',
      'sell_no_categories': 'பிரிவுகள் எதுவும் காணப்படவில்லை',
      'sell_retry': 'மீண்டும் முயற்சி செய்',
      'sell_error_categories': 'பிரிவுகளை ஏற்ற முடியவில்லை.',
      'sell_back': 'பின்னே செல்',
      'sell_select_subcategory': 'துணைப் பிரிவைத் தேர்ந்தெடுக்கவும்',
      'sell_selected_category': 'தேர்ந்தெடுக்கப்பட்ட பிரிவு: ',
      'sell_change_by_back': 'பின்னே செல்வதன் மூலம் இதை நீங்கள் மாற்றலாம்',
      'sell_change': 'மாற்று',
      'sell_no_subcategories': 'துணைப் பிரிவுகள் எதுவும் காணப்படவில்லை',
      'sell_subcategory_hint':
          'அதிகப்படியான வாங்குபவர்களைச் சென்றடைய, உங்கள் விளம்பரத்திற்கு மிகவும் பொருத்தமான துணைப் பிரிவைத் தேர்ந்தெடுக்கவும்.',
      'sell_error_subcategories': 'துணைப் பிரிவுகளை ஏற்ற முடியவில்லை.',
      'sell_product_title': 'பொருளின் தலைப்பு',
      'sell_title_hint': 'பொருளின் பெயரை உள்ளிடவும் (எ.கா. BMW X5 2024)',
      'sell_description': 'விளக்கம்',
      'sell_desc_hint': 'விரிவான விளக்கத்தை உள்ளிடவும்...',
      'sell_features': 'அம்சங்கள் (காற்புள்ளியால் பிரிக்கவும்)',
      'sell_features_hint': 'சன்ரூஃப், லெதர் இருக்கைகள், ஆட்டோபைலட்...',
      'sell_main_image': 'பொருளின் முக்கிய புகைப்படம்',
      'sell_no_file': 'கோப்பு எதுவும் தேர்ந்தெடுக்கப்படவில்லை',
      'sell_choose_file': 'கோப்பைத் தேர்ந்தெடு',
      'sell_gallery_images': 'கேலரி புகைப்படங்கள்',
      'sell_max_images': 'அதிகபட்சம் 5 புகைப்படங்கள்',
      'sell_price': 'விலை (₹)',
      'sell_discount': 'தள்ளுபடி (%)',
      'sell_total_cost': 'மொத்த விலை (₹)',
      'sell_capacity': 'கொள்ளளவு (Capacity)',
      'sell_warranty': 'உத்தரவாதம் (Warranty)',
      'sell_active_product': 'செயலில் உள்ள பொருள்',
      'sell_save_product': 'பொருளைச் சேமி',
      'sell_select_main_image':
          'தயவுசெய்து பொருளின் முக்கிய புகைப்படத்தைத் தேர்ந்தெடுக்கவும்.',
      'sell_required': 'தேவையானது',
      'sell_error_saving': 'பொருளைச் சேமிக்கும் போது ஏதோ தவறு நடந்தது.',
      'sell_review': 'மதிப்பாய்வு',
      'sell_review_title': 'உங்கள் விண்ணப்பம் பரிசீலனையில் உள்ளது',
      'sell_review_desc':
          'உங்கள் பொருளின் விவரங்களைப் பெற்றுள்ளோம். எங்களது குழு விரைவில் அதை மதிப்பாய்வு செய்யும்.',
      'sell_go_dashboard': 'டாஷ்போர்டிற்குச் செல்',

      // Available Jobs
      'jobs_available_title': 'கிடைக்கக்கூடிய வேலைகள்',
      'jobs_no_jobs_found':
          'இந்தப்பணிக்கு எந்த வேலை வாய்ப்புகளும் காணப்படவில்லை.',
      'jobs_loading': 'வேலை வாய்ப்புகள் ஏற்றப்படுகின்றன...',
      'jobs_error': 'வேலை வாய்ப்புகளை ஏற்ற முடியவில்லை.',
      'jobs_vacancy': 'காலியிடம்',
      'jobs_vacancies': 'காலியிடங்கள்',
      'jobs_walkin': 'நேரடி நேர்காணல் (Walk-in)',
      'jobs_apply': 'விண்ணப்பி',
      'jobs_salary_range': 'சம்பளம்',
      'jobs_experience': 'அனுபவம்',
      'jobs_applications': 'விண்ணப்பங்கள்',
      'jobs_view_details': 'விவரங்களைப் பார்',
    },
    'mr': {
      // General / common
      'app_title': 'रोजगार अड्डा',
      'app_logo_text': 'रोजगार',
      'sidebar_username': 'रोजगार उपयोगकर्ता',
      'ok': 'ठीक आहे',
      'cancel': 'रद्द करा',
      'continue': 'पुढे जा',
      'back': 'मागे',
      'view_all': 'सर्व पहा',

      // Splash
      'splash_tagline': 'संधींचे तुमचे प्रवेशद्वार',
      'splash_launching': 'तुमचे भविष्य सुरू होत आहे...',
      'splash_secure_verified': 'सुरक्षित आणि सत्यापित नोकऱ्या',

      // Login
      'login_title': 'रोजगार अड्डा',
      'login_welcome_back': 'पुन्हा आपले स्वागत आहे',
      'login_subtitle':
          'तुमच्या जॉब पोर्टलवर लॉग इन करण्यासाठी तुमची माहिती प्रविष्ट करा',
      'login_email_label': 'ईमेल पत्ता',
      'login_email_hint': 'name@company.com',
      'login_password_label': 'पासवर्ड',
      'login_forgot': 'पासवर्ड विसरलात?',
      'login_button': 'लॉग इन करा',
      'login_no_account': 'खाते नाही का? ',
      'login_register': 'नोंदणी करा',
      'login_error_title': 'लॉग इन अयशस्वी',
      'login_error_empty':
          'कृपया वापरकर्तानाव (username) आणि पासवर्ड प्रविष्ट करा.',

      // Registration
      'registration_progress': 'नोंदणी प्रगती',
      'registration_step': 'टप्पा १ पैकी ३',
      'registration_personal_info': 'वैयक्तिक माहिती',
      'registration_full_name': 'पूर्ण नाव',
      'registration_full_name_hint': 'तुमचे पूर्ण नाव प्रविष्ट करा',
      'registration_phone_number': 'मोबाईल नंबर',
      'registration_email': 'ईमेल पत्ता',
      'registration_email_hint': 'name@example.com',
      'registration_address_details': 'पत्ता तपशील',
      'registration_state': 'राज्य',
      'registration_select_state': 'राज्य निवडा',
      'registration_district': 'जिल्हा',
      'registration_area': 'क्षेत्र / परिसर',
      'registration_area_hint': 'क्षेत्र',
      'registration_pincode': 'पिनकोड',
      'registration_pincode_hint': '********',
      'registration_full_address': 'पूर्ण पत्ता',
      'registration_full_address_hint': 'घर क्रमांक, गल्लीचे नाव...',
      'registration_identity_verification': 'ओळख पडताळणी',
      'registration_account_credentials': 'खात्याची माहिती',
      'registration_username': 'वापरकर्तानाव (Username)',
      'registration_username_hint': 'एक युनिक वापरकर्तानाव निवडा',
      'registration_password': 'पासवर्ड',
      'registration_terms_prefix': 'मी नियम आणि अटींशी ',
      'registration_terms_link': 'सहमत आहे',
      'registration_create_account': 'खाते तयार करा',
      'registration_already_account': 'आधीच खाते आहे का? ',
      'registration_login': 'लॉग इन करा',
      'registration_join_tagline': 'कार्यबलात सामील व्हा',
      'registration_verify_otp': 'ओटीपी सत्यापित करा',
      'registration_send_otp': 'ओटीपी पाठवा',
      'registration_otp_hint': 'फोनवर पाठवलेला 6-अंकी ओटीपी प्रविष्ट करा',
      'registration_otp_resend': 'ओटीपी पुन्हा पाठवा',
      'registration_otp_resend_in': 'पुन्हा पाठवा',
      'registration_otp_resend_sec': 'से.',
      'registration_phone_verified': '✓ सत्यापित',
      'registration_error_otp_phone':
          'कृपया वैध 10-अंकी फोन नंबर प्रविष्ट करा.',
      'registration_error_otp_incomplete':
          'कृपया संपूर्ण 6-अंकी ओटीपी प्रविष्ट करा.',
      'registration_otp_sent_success': 'ओटीपी तुमच्या नंबरवर पाठवला!',
      'registration_otp_verify_success': 'फोन नंबर यशस्वीरीत्या सत्यापित झाला!',
      'registration_error_fields': 'कृपया सर्व आवश्यक फील्ड भरा.',
      'registration_error_state': 'कृपया एक राज्य निवडा.',
      'registration_error_district': 'कृपया एक जिल्हा निवडा.',
      'registration_error_terms':
          'कृपया पुढे जाण्यासाठी नियम आणि गोपनीयता धोरण स्वीकारा.',
      'registration_error_phone_verify':
          'कृपया प्रथम तुमचा फोन नंबर सत्यापित करा.',
      'registration_upload_title': 'ओळखपत्र अपलोड करा',
      'registration_upload_hint':
          'आधार कार्ड, पॅन किंवा मतदार ओळखपत्र (JPG/PDF, कमाल 2MB)',
      'registration_choose_file': 'फाइल निवडा',
      'registration_password_hint': 'किमान ८ अक्षरे',
      'registration_terms_privacy': 'गोपनीयता धोरण',
      'registration_terms_and': ' आणि ',
      'registration_terms_suffix': ' शी सहमत आहे.',

      // Select State
      'select_state_appbar': 'राज्य निवडा / Select State',
      'select_state_step_label': 'टप्पा २ पैकी ३',
      'select_state_progress': '६६% पूर्ण',
      'select_state_heading': 'तुम्ही कुठे नोकरी शोधत आहात?',
      'select_state_subheading':
          'तुमच्यासाठी खास तयार केलेल्या सर्वोत्तम स्थानिक संधी पाहण्यासाठी तुमचे राज्य निवडा',
      'select_state_search_hint': 'राज्याचे नाव शोधा...',

      // Language dialog
      'language_dialog_title': 'भाषा निवडा',
      'language_dialog_message':
          'तुमची पसंतीची ॲप भाषा निवडा. तुम्ही ती नंतर कधीही बदलू शकता.',
      'language_english': 'इंग्रजी (English)',
      'language_hindi': 'हिंदी (Hindi)',

      // Home / navigation
      'nav_home': 'मुख्यपृष्ठ',
      'nav_explore': 'शोध घ्या',
      'nav_saved': 'जतन केलेले',
      'nav_profile': 'प्रोफाइल',

      // Explore careers / job categories
      'explore_careers_title': 'करिअरचे पर्याय शोधा',
      'explore_job_categories': 'नोकरीच्या श्रेणी',
      'explore_job_categories_subtitle':
          'विविध उद्योगांमध्ये तुमच्यासाठी योग्य भूमिका शोधा',
      'explore_opportunities_pill': 'संधी',
      'explore_custom_search': 'कस्टम सर्च',
      'explore_custom_search_sub': 'तुमच्या कौशल्यांवर आधारित नोकऱ्या शोधा',

      // Career hub / job list
      'careerhub_title': 'करिअरहब (CareerHub)',
      'careerhub_search_hint': 'नोकऱ्या, कंपन्या शोधा...',
      'careerhub_tab_all': 'सर्व नोकऱ्या',
      'careerhub_tab_remote': 'रिमोट (घरून काम)',
      'careerhub_tab_fulltime': 'पूर्ण वेळ',
      'careerhub_tab_salary': 'पगार',

      // Job detail
      'jobdetail_appbar_title': 'नोकरीची संधी',
      'jobdetail_annual_salary': 'वार्षिक पगार',
      'jobdetail_experience': 'अनुभव',
      'jobdetail_applicants': 'अर्जदार',
      'jobdetail_role_description': 'भूमिकेचे वर्णन (Role Description)',
      'jobdetail_requirements': 'आवश्यकता',
      'jobdetail_location': 'ठिकाण',
      'jobdetail_apply_now': 'आता अर्ज करा',

      // Job application form
      'apply_header_title': 'सीनिअर प्रॉडक्ट डिझायनर',
      'apply_step_label': 'टप्पा २ पैकी ४:\nअनुभव',
      'apply_complete': 'पूर्ण झाले',
      'apply_personal_info': 'वैयक्तिक माहिती',
      'apply_first_name': 'पहिले नाव',
      'apply_last_name': 'आडनाव',
      'apply_email': 'ईमेल पत्ता',
      'apply_professional_details': 'व्यावसायिक तपशील',
      'apply_current_position': 'सध्याचे पद',
      'apply_linkedin': 'लिंक्डइन प्रोफाइल (LinkedIn)',
      'apply_resume_upload': 'रेझ्युमे अपलोड (Resume Upload)',
      'apply_upload_cta':
          'अपलोड करण्यासाठी क्लिक करा किंवा फाइल येथे ड्रॅग करा',
      'apply_upload_hint': 'कमाल फाइल आकार १०MB • PDF किंवा DOCX',
      'apply_why_hire': 'आम्ही तुमची निवड का करावी?',
      'apply_why_hire_hint':
          'तुमच्या अनुभवाबद्दल आणि तुम्ही या भूमिकेसाठी योग्य का आहात याबद्दल थोडक्यात सांगा.',
      'apply_agree':
          'मी माझ्या अर्जाचा तपशील नियोक्त्यासोबत (employer) शेअर करण्यास सहमत आहे.',
      'apply_submit': 'अर्ज सबमिट करा',
      'apply_footer':
          'सबमिट करून, तुम्ही आमच्या गोपनीयता धोरण आणि अटींशी सहमत आहात.',
      'dashboard_search_hint': 'नोकऱ्या, कंपन्या शोधा...',
      'dashboard_quick_links': 'त्वरित दुवे',
      'dashboard_new_job_badge': 'नवीन नोकरी',
      'dashboard_recent_activity': 'अलीकडील क्रियाकलाप',
      'dashboard_location': 'जयपूर, राजस्थान',
      'find_jobs': 'नोकऱ्या शोधा',
      'kyc_status': 'केवायसी स्थिती',
      'sell_products': 'उत्पादने विका',
      'marketplace': 'मार्केटप्लेस',
      'earnings': 'कमाई',
      'support': 'मदत व सपोर्ट',
      'news': 'बातम्या',
      'missing_persons': 'बेपत्ता व्यक्ती',
      'missing_persons_coming_soon': 'बेपत्ता व्यक्ती वैशिष्ट्य लवकरच येत आहे!',
      'skill_up': 'कौशल्यांचा विकास',
      'home': 'मुख्यपृष्ठ',
      'products': 'उत्पादने',
      'settings': 'सेटिंग्ज',
      'logout': 'लॉगआउट',
      'worker_kyc_verified': 'कामगार • केवायसी सत्यापित',
      'menu': 'मेनू',
      'registration_success_title': 'नोंदणी यशस्वी',
      'registration_success_message':
          'तुम्ही या ईमेलसह यशस्वीरीत्या नोंदणी केली आहे: ',

      // Profile screen
      'profile_my_profile': 'माझी प्रोफाइल',
      'profile_id_label': 'आयडी',
      'profile_edit_profile': 'प्रोफाइल संपादित करा',
      'profile_kyc_status': 'केवायसी स्थिती',
      'profile_my_products': 'माझी उत्पादने',
      'profile_my_applications': 'माझे अर्ज',
      'profile_change_password': 'पासवर्ड बदला',
      'profile_help_support': 'मदत आणि सपोर्ट',
      'logout_confirm_title': 'लॉगआउट',
      'logout_confirm_message': 'तुम्हाला खरोखर लॉगआउट करायचे आहे का?',

      // Splash menu
      'splash_menu_home': 'मुख्य स्क्रीन',
      'splash_menu_about': 'आमच्याबद्दल',
      'splash_menu_missing': 'बेपत्ता',
      'splash_menu_news': 'बातम्या',
      'splash_menu_product': 'उत्पादन',
      'splash_menu_register': 'उमेदवार नोंदणी',
      'splash_menu_login': 'उमेदवार लॉगिन',

      // Login extras
      'login_terms_agree': 'मी सेवा अटी आणि गोपनीयता धोरणाशी सहमत आहे.',
      'login_terms_error':
          'कृपया पुढे जाण्यासाठी नियम आणि गोपनीयता धोरण स्वीकारा.',
      'login_or_continue': 'किंवा यासह सुरू ठेवा',
      'login_sign_in': 'साइन इन',
      'login_error_generic': 'काहीतरी चूक झाली. कृपया पुन्हा प्रयत्न करा.',

      // KYC screen
      'kyc_title': 'केवायसी तपशील संपादित करा',
      'kyc_subtitle': 'तुमची केवायसी माहिती अद्यतनित करा',
      'kyc_subtitle_id': 'उमेदवार क्रमांकाची केवायसी माहिती अद्यतनित करा #',
      'kyc_status_pending': 'स्थिती: प्रलंबित',
      'kyc_section_personal': 'वैयक्तिक माहिती',
      'kyc_section_address': 'पत्ता माहिती',
      'kyc_section_documents': 'कागदपत्रे अपलोड',
      'kyc_docs_hint':
          'स्पष्ट, वाचनीय प्रती अपलोड करा. समर्थित: JPG, PNG, PDF, DOC',
      'kyc_field_full_name': 'पूर्ण नाव',
      'kyc_field_phone': 'मोबाईल नंबर',
      'kyc_field_email': 'ईमेल पत्ता',
      'kyc_field_state': 'राज्य',
      'kyc_field_district': 'जिल्हा',
      'kyc_field_locality': 'परिसर/क्षेत्र',
      'kyc_field_pincode': 'पिनकोड',
      'kyc_field_address': 'पूर्ण पत्ता',
      'kyc_address_hint': 'फ्लॅट क्र., इमारत, रस्ता...',
      'kyc_identity_title': 'ओळखपत्र',
      'kyc_identity_subtitle': 'आधार, पॅन किंवा पासपोर्ट',
      'kyc_resume_title': 'रेझ्युमे / CV',
      'kyc_resume_subtitle': 'PDF किंवा Word स्वरूप',
      'kyc_photo_title': 'प्रोफाइल फोटो',
      'kyc_photo_subtitle': 'अलीकडील पासपोर्ट आकाराचा फोटो',
      'kyc_update_button': 'केवायसी अद्यतनित करा',
      'kyc_image_source_title': 'प्रतिमा स्रोत निवडा',
      'kyc_source_camera': 'कॅमेरा',
      'kyc_source_gallery': 'गॅलरी',
      'kyc_snack_photo_uploaded': 'फोटो यशस्वीरित्या अपलोड झाला!',
      'kyc_snack_doc_uploaded': 'दस्तऐवज यशस्वीरित्या अपलोड झाला!',
      'kyc_snack_file_removed': 'फाइल काढली.',
      'kyc_snack_missing_docs': 'कृपया सर्व आवश्यक कागदपत्रे अपलोड करा.',
      'kyc_snack_missing_fields': 'कृपया सर्व आवश्यक फील्ड भरा.',
      'kyc_snack_invalid_phone': 'कृपया वैध 10-अंकी मोबाईल नंबर प्रविष्ट करा.',
      'kyc_snack_invalid_pin': 'कृपया वैध 6-अंकी पिनकोड प्रविष्ट करा.',
      'kyc_snack_invalid_email': 'कृपया वैध ईमेल पत्ता प्रविष्ट करा.',
      'kyc_snack_no_candidate':
          'उमेदवार आयडी सापडला नाही. कृपया पुन्हा लॉगिन करा.',
      'kyc_snack_updated': 'केवायसी यशस्वीरित्या अद्यतनित केले',
      'kyc_snack_failed':
          'केवायसी अद्यतन करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
      'kyc_snack_error':
          'केवायसी अद्यतन करताना काहीतरी चूक झाली. कृपया आपले कनेक्शन तपासा.',
      'kyc_upload_label': 'अपलोड',

      // News screen
      'news_title': 'रोजगार बातम्या',
      'news_trending_now': 'आत्ता ट्रेंडिंग',
      'news_header_title': 'आधुनिक कार्यबलासाठी\nकरिअर अंतर्दृष्टी',
      'news_read_more': 'अधिक वाचा ',
      'news_mins_read': '५ मिनिटे वाचन',
      'news_tab_all': 'सर्व बातम्या',
      'news_tab_articles': 'लेख',
      'news_tab_videos': 'व्हिडिओ',
      'news_error_loading': 'बातम्या लोड करण्यात अयशस्वी.',
      'news_empty_list': 'कोणत्याही बातम्या उपलब्ध नाहीत.',

      // Sell Product Screen
      'sell_post_ad': 'आपली जाहिरात द्या',
      'sell_choose_category': 'श्रेणी निवडा',
      'sell_next': 'पुढे',
      'sell_category': 'श्रेणी',
      'sell_sub_category': 'उप श्रेणी',
      'sell_details': 'तपशील',
      'sell_no_categories': 'कोणत्याही श्रेणी आढळल्या नाहीत',
      'sell_retry': 'पुन्हा प्रयत्न करा',
      'sell_error_categories': 'श्रेणी लोड करण्यात अक्षम.',
      'sell_back': 'मागे',
      'sell_select_subcategory': 'उप श्रेणी निवडा',
      'sell_selected_category': 'निवडलेली श्रेणी: ',
      'sell_change_by_back': 'तुम्ही मागे जाऊन हे बदलू शकता',
      'sell_change': 'बदला',
      'sell_no_subcategories': 'कोणत्याही उप-श्रेण्या आढळल्या नाहीत',
      'sell_subcategory_hint':
          'अधिक खरेदीदारांपर्यंत पोहोचण्यासाठी आपल्या जाहिरातीसाठी सर्वात संबंधित उप-श्रेणी निवडा.',
      'sell_error_subcategories': 'उप-श्रेण्या लोड करण्यात अक्षम.',
      'sell_product_title': 'उत्पादनाचे शीर्षक',
      'sell_title_hint': 'उत्पादनाचे नाव प्रविष्ट करा',
      'sell_description': 'वर्णन',
      'sell_desc_hint': 'तपशीलवार वर्णन प्रविष्ट करा',
      'sell_features': 'वैशिष्ट्ये (कॉमाने वेगळी करा)',
      'sell_features_hint': 'वैशिष्ट्ये',
      'sell_main_image': 'मुख्य उत्पादन प्रतिमा',
      'sell_no_file': 'कोणतीही फाईल निवडली नाही',
      'sell_choose_file': 'फाइल निवडा',
      'sell_gallery_images': 'गॅलरी प्रतिमा',
      'sell_max_images': 'कमाल ५ प्रतिमा',
      'sell_price': 'किंमत (₹)',
      'sell_discount': 'सवलत (%)',
      'sell_total_cost': 'एकूण किंमत (₹)',
      'sell_capacity': 'क्षमता',
      'sell_warranty': 'हमी/वारंटी',
      'sell_active_product': 'सक्रिय उत्पादन',
      'sell_save_product': 'उत्पादन जतन करा',
      'sell_select_main_image': 'कृपया मुख्य उत्पादन प्रतिमा निवडा.',
      'sell_required': 'आवश्यक',
      'sell_error_saving': 'उत्पादन जतन करताना काहीतरी चुकले.',
      'sell_review': 'पुनरावलोकन',
      'sell_review_title': 'तुमचा अर्ज पुनरावलोकनाधीन आहे',
      'sell_review_desc':
          'आम्हाला तुमच्या उत्पादनाचा तपशील प्राप्त झाला आहे. आमची टीम लवकरच याचे पुनरावलोकन करेल.',
      'sell_go_dashboard': 'डॅशबोर्डवर जा',

      // Available Jobs
      'jobs_available_title': 'उपलब्ध नोकऱ्या',
      'jobs_no_jobs_found': 'या भूमिकेसाठी कोणतीही नोकरी उपलब्ध नाही.',
      'jobs_loading': 'नोकरीच्या संधी लोड होत आहेत...',
      'jobs_error': 'नोकरीच्या संधी लोड करता आल्या नाहीत.',
      'jobs_vacancy': 'रिक्त जागा',
      'jobs_vacancies': 'रिक्त जागा',
      'jobs_walkin': 'वॉक-इन',
      'jobs_apply': 'अर्ज करा',
      'jobs_salary_range': 'पगार',
      'jobs_experience': 'अनुभव',
      'jobs_applications': 'अर्ज',
      'jobs_view_details': 'तपशील पहा',
    },
    'hi': {
      // General / common
      'app_title': 'रोज़गार अड्डा',
      'app_logo_text': 'रोज़गार',
      'sidebar_username': 'रोजगार उपयोगकर्ता',
      'ok': 'ठीक है',
      'cancel': 'रद्द करें',
      'continue': 'आगे बढ़ें',
      'back': 'वापस',
      'view_all': 'सभी देखें',

      // Splash
      'splash_tagline': 'आपके अवसरों का द्वार',
      'splash_launching': 'आपका भविष्य शुरू हो रहा है...',
      'splash_secure_verified': 'सुरक्षित और सत्यापित नौकरियां',

      // Login
      'login_title': 'रोज़गार अड्डा',
      'login_welcome_back': 'दोबारा स्वागत है',
      'login_subtitle': 'अपना जॉब पोर्टल एक्सेस करने के लिए विवरण दर्ज करें',
      'login_email_label': 'ईमेल पता',
      'login_email_hint': 'name@company.com',
      'login_password_label': 'पासवर्ड',
      'login_forgot': 'भूल गए?',
      'login_button': 'लॉगिन',
      'login_no_account': 'अब तक खाता नहीं है? ',
      'login_register': 'रजिस्टर करें',
      'login_error_title': 'लॉगिन विफल',
      'login_error_empty': 'कृपया उपयोगकर्ता नाम और पासवर्ड दर्ज करें।',

      // Registration
      'registration_progress': 'पंजीकरण प्रगति',
      'registration_step': 'स्टेप 1 / 3',
      'registration_personal_info': 'व्यक्तिगत जानकारी',
      'registration_full_name': 'पूरा नाम',
      'registration_full_name_hint': 'अपना पूरा नाम दर्ज करें',
      'registration_phone_number': 'मोबाइल नंबर',
      'registration_email': 'ईमेल पता',
      'registration_email_hint': 'name@example.com',
      'registration_address_details': 'पता विवरण',
      'registration_state': 'राज्य',
      'registration_select_state': 'राज्य चुनें',
      'registration_district': 'ज़िला',
      'registration_area': 'क्षेत्र / लोकैलिटी',
      'registration_area_hint': 'क्षेत्र',
      'registration_pincode': 'पिनकोड',
      'registration_pincode_hint': '000000',
      'registration_full_address': 'पूरा पता',
      'registration_full_address_hint': 'मकान नंबर, गली का नाम...',
      'registration_identity_verification': 'पहचान सत्यापन',
      'registration_account_credentials': 'अकाउंट विवरण',
      'registration_username': 'यूज़रनेम',
      'registration_username_hint': 'एक यूनिक यूज़रनेम चुनें',
      'registration_password': 'पासवर्ड',
      'registration_terms_prefix': 'मैं ',
      'registration_terms_link': 'नियम और शर्तें',
      'registration_create_account': 'अकाउंट बनाएं',
      'registration_already_account': 'पहले से अकाउंट है? ',
      'registration_login': 'लॉगिन',
      'registration_join_tagline': 'कार्यबल में शामिल हों',
      'registration_verify_otp': 'ओटीपी सत्यापित करें',
      'registration_send_otp': 'ओटीपी भेजें',
      'registration_otp_hint': 'फ़ोन पर भेजा गया 6-अंकीय ओटीपी दर्ज करें',
      'registration_otp_resend': 'ओटीपी दोबारा भेजें',
      'registration_otp_resend_in': 'दोबारा भेजें',
      'registration_otp_resend_sec': 'सेकंड',
      'registration_phone_verified': '✓ सत्यापित',
      'registration_error_otp_phone': 'कृपया वैध 10-अंकीय फ़ोन नंबर दर्ज करें।',
      'registration_error_otp_incomplete':
          'कृपया पूरा 6-अंकीय ओटीपी दर्ज करें।',
      'registration_otp_sent_success': 'ओटीपी आपके नंबर पर भेज दिया गया!',
      'registration_otp_verify_success':
          'फ़ोन नंबर सफलतापूर्वक सत्यापित हो गया!',
      'registration_error_fields': 'कृपया सभी आवश्यक फ़ील्ड भरें।',
      'registration_error_state': 'कृपया एक राज्य चुनें।',
      'registration_error_district': 'कृपया एक ज़िला चुनें।',
      'registration_error_terms':
          'कृपया आगे बढ़ने के लिए नियम और गोपनीयता नीति स्वीकार करें।',
      'registration_error_phone_verify':
          'कृपया पहले अपना फ़ोन नंबर सत्यापित करें।',
      'registration_upload_title': 'पहचान प्रमाण अपलोड करें',
      'registration_upload_hint':
          'आधार कार्ड, पैन, या मतदाता पहचान पत्र (JPG/PDF, अधिकतम 2MB)',
      'registration_choose_file': 'फ़ाइल चुनें',
      'registration_password_hint': 'कम से कम 8 वर्ण',
      'registration_terms_privacy': 'गोपनीयता नीति',
      'registration_terms_and': ' और ',
      'registration_terms_suffix': ' से सहमत हूँ।',

      // Select State
      'select_state_appbar': 'राज्य चुनें',
      'select_state_step_label': 'स्टेप 2 / 3',
      'select_state_progress': '66% पूरा',
      'select_state_heading': 'आप कहां नौकरी ढूंढ रहे हैं?',
      'select_state_subheading':
          'अपने राज्य का चयन करें ताकि आपके लिए स्थानीय अवसर दिखाए जा सकें',
      'select_state_search_hint': 'राज्य का नाम खोजें...',

      // Language dialog
      'language_dialog_title': 'भाषा चुनें',
      'language_dialog_message':
          'अपनी पसंदीदा ऐप भाषा चुनें। आप इसे बाद में भी बदल सकते हैं।',
      'language_english': 'अंग्रेज़ी',
      'language_hindi': 'हिंदी',

      // Home / navigation
      'nav_home': 'होम',
      'nav_explore': 'एक्सप्लोर',
      'nav_saved': 'सेव्ड',
      'nav_profile': 'प्रोफ़ाइल',

      // Explore careers / job categories
      'explore_careers_title': 'करियर खोजें',
      'explore_job_categories': 'जॉब कैटेगरी',
      'explore_job_categories_subtitle':
          'विभिन्न उद्योगों में सही भूमिका खोजें',
      'explore_opportunities_pill': 'अवसर',
      'explore_custom_search': 'कस्टम सर्च',
      'explore_custom_search_sub': 'अपनी स्किल के अनुसार नौकरी खोजें',

      // Career hub / job list
      'careerhub_title': 'करियर हब',
      'careerhub_search_hint': 'नौकरियां, कंपनियां खोजें...',
      'careerhub_tab_all': 'सभी नौकरियां',
      'careerhub_tab_remote': 'रिमोट',
      'careerhub_tab_fulltime': 'फुल-टाइम',
      'careerhub_tab_salary': 'सैलरी',

      // Job detail
      'jobdetail_appbar_title': 'जॉब अवसर',
      'jobdetail_annual_salary': 'वार्षिक वेतन',
      'jobdetail_experience': 'अनुभव',
      'jobdetail_applicants': 'आवेदक',
      'jobdetail_role_description': 'भूमिका विवरण',
      'jobdetail_requirements': 'आवश्यकताएँ',
      'jobdetail_location': 'स्थान',
      'jobdetail_apply_now': 'अभी आवेदन करें',

      // Job application form
      'apply_header_title': 'सीनियर प्रोडक्ट डिज़ाइनर',
      'apply_step_label': 'स्टेप 2 / 4:\nअनुभव',
      'apply_complete': 'पूरा',
      'apply_personal_info': 'व्यक्तिगत जानकारी',
      'apply_first_name': 'पहला नाम',
      'apply_last_name': 'अंतिम नाम',
      'apply_email': 'ईमेल पता',
      'apply_professional_details': 'प्रोफेशनल विवरण',
      'apply_current_position': 'वर्तमान पद',
      'apply_linkedin': 'लिंक्डइन प्रोफाइल',
      'apply_resume_upload': 'रिज़्यूमे अपलोड',
      'apply_upload_cta': 'क्लिक कर अपलोड करें या ड्रैग और ड्रॉप करें',
      'apply_upload_hint': 'अधिकतम फ़ाइल साइज़ 10MB • केवल PDF या DOCX',
      'apply_why_hire': 'हमें आपको क्यों रखना चाहिए?',
      'apply_why_hire_hint':
          'संक्षेप में हमें अपने अनुभव और इस भूमिका के लिए अपनी उपयुक्तता के बारे में बताएं।',
      'apply_agree':
          'मैं अपनी एप्लिकेशन डिटेल्स नियोक्ता के साथ साझा करने के लिए सहमत हूँ।',
      'apply_submit': 'आवेदन सबमिट करें',
      'apply_footer':
          'सबमिट करके, आप हमारी प्राइवेसी नीति और नियमों से सहमत होते हैं.',
      'dashboard_search_hint': 'नौकरियां, कंपनियां खोजें...',
      'dashboard_quick_links': 'त्वरित लिंक्स',
      'dashboard_new_job_badge': 'नई नौकरी',
      'dashboard_recent_activity': 'हाल की गतिविधि',
      'dashboard_location': 'जयपुर, राजस्थान',
      'find_jobs': 'नौकरियां खोजें',
      'kyc_status': 'केवाईसी स्थिति',
      'sell_products': 'उत्पाद बेचें',
      'marketplace': 'मार्केटप्लेस',
      'earnings': 'कमाई',
      'support': 'सहायता',
      'news': 'समाचार',
      'missing_persons': 'लापता व्यक्ति',
      'missing_persons_coming_soon': 'लापता व्यक्ति सुविधा जल्द ही आ रही है!',
      'skill_up': 'कौशल बढ़ाएं',
      'home': 'होम',
      'products': 'उत्पाद',
      'settings': 'सेटिंग्स',
      'logout': 'लॉगआउट',
      'worker_kyc_verified': 'श्रमिक • केवाईसी सत्यापित',
      'menu': 'मेनू',
      'registration_success_title': 'पंजीकरण सफल',
      'registration_success_message':
          'आपने इस ईमेल के साथ सफलतापूर्वक पंजीकरण किया है: ',

      // Profile screen
      'profile_my_profile': 'मेरी प्रोफ़ाइल',
      'profile_id_label': 'आईडी',
      'profile_edit_profile': 'प्रोफ़ाइल संपादित करें',
      'profile_kyc_status': 'केवाईसी स्थिति',
      'profile_my_products': 'मेरे उत्पाद',
      'profile_my_applications': 'मेरे आवेदन',
      'profile_change_password': 'पासवर्ड बदलें',
      'profile_help_support': 'सहायता और सपोर्ट',
      'logout_confirm_title': 'लॉगआउट',
      'logout_confirm_message': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',

      // Splash menu
      'splash_menu_home': 'होम स्क्रीन',
      'splash_menu_about': 'हमारे बारे में',
      'splash_menu_missing': 'लापता',
      'splash_menu_news': 'समाचार',
      'splash_menu_product': 'उत्पाद',
      'splash_menu_register': 'उम्मीदवार पंजीकरण',
      'splash_menu_login': 'उम्मीदवार लॉगिन',

      // Login extras
      'login_terms_agree': 'मैं सेवा की शर्तें और गोपनीयता नीति से सहमत हूँ।',
      'login_terms_error':
          'कृपया आगे बढ़ने के लिए नियम और गोपनीयता नीति स्वीकार करें।',
      'login_or_continue': 'या इसके साथ जारी रखें',
      'login_sign_in': 'साइन इन',
      'login_error_generic': 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।',

      // KYC screen
      'kyc_title': 'KYC विवरण संपादित करें',
      'kyc_subtitle': 'अपनी KYC जानकारी अपडेट करें',
      'kyc_subtitle_id': 'उम्मीदवार की KYC जानकारी अपडेट करें #',
      'kyc_status_pending': 'स्थिति: लंबित',
      'kyc_section_personal': 'व्यक्तिगत जानकारी',
      'kyc_section_address': 'पता जानकारी',
      'kyc_section_documents': 'दस्तावेज़ अपलोड',
      'kyc_docs_hint':
          'स्पष्ट, पठनीय प्रतियाँ अपलोड करें। समर्थित: JPG, PNG, PDF, DOC',
      'kyc_field_full_name': 'पूरा नाम',
      'kyc_field_phone': 'मोबाइल नंबर',
      'kyc_field_email': 'ईमेल पता',
      'kyc_field_state': 'राज्य',
      'kyc_field_district': 'ज़िला',
      'kyc_field_locality': 'लोकैलिटी/क्षेत्र',
      'kyc_field_pincode': 'पिनकोड',
      'kyc_field_address': 'पूरा पता',
      'kyc_address_hint': 'फ्लैट नं., इमारत, गली...',
      'kyc_identity_title': 'पहचान प्रमाण',
      'kyc_identity_subtitle': 'आधार, PAN या पासपोर्ट',
      'kyc_resume_title': 'रिज़्यूमे / CV',
      'kyc_resume_subtitle': 'PDF या Word प्रारूप',
      'kyc_photo_title': 'प्रोफ़ाइल फोटो',
      'kyc_photo_subtitle': 'हालिया पासपोर्ट साइज़ फोटो',
      'kyc_update_button': 'KYC अपडेट करें',
      'kyc_image_source_title': 'छवि स्रोत चुनें',
      'kyc_source_camera': 'कैमरा',
      'kyc_source_gallery': 'गैलरी',
      'kyc_snack_photo_uploaded': 'फोटो सफलतापूर्वक अपलोड हुआ!',
      'kyc_snack_doc_uploaded': 'दस्तावेज़ सफलतापूर्वक अपलोड हुआ!',
      'kyc_snack_file_removed': 'फ़ाइल हटाई गई।',
      'kyc_snack_missing_docs': 'कृपया सभी आवश्यक दस्तावेज़ अपलोड करें।',
      'kyc_snack_missing_fields': 'कृपया सभी आवश्यक फ़ील्ड भरें।',
      'kyc_snack_invalid_phone': 'कृपया वैध 10-अंकीय मोबाइल नंबर दर्ज करें।',
      'kyc_snack_invalid_pin': 'कृपया वैध 6-अंकीय पिनकोड दर्ज करें।',
      'kyc_snack_invalid_email': 'कृपया वैध ईमेल पता दर्ज करें।',
      'kyc_snack_no_candidate':
          'उम्मीदवार आईडी नहीं मिली। कृपया पुनः लॉगिन करें।',
      'kyc_snack_updated': 'KYC सफलतापूर्वक अपडेट हुई',
      'kyc_snack_failed': 'KYC अपडेट करने में विफल। कृपया पुनः प्रयास करें।',
      'kyc_snack_error':
          'KYC अपडेट करते समय कुछ गलत हो गया। कृपया अपना कनेक्शन जाँचें।',
      'kyc_upload_label': 'अपलोड',

      // News screen
      'news_title': 'रोज़गार समाचार',
      'news_trending_now': 'अभी ट्रेंडिंग',
      'news_header_title': 'आधुनिक कार्यबल के लिए\nकरियर अंतर्दृष्टि',
      'news_read_more': 'और पढ़ें ',
      'news_mins_read': '५ मिनट पढ़ना',
      'news_tab_all': 'सभी समाचार',
      'news_tab_articles': 'लेख',
      'news_tab_videos': 'वीडियो',
      'news_error_loading': 'समाचार लोड करने में विफल।',
      'news_empty_list': 'कोई समाचार उपलब्ध नहीं है।',

      // Sell Product Screen
      'sell_post_ad': 'अपना विज्ञापन पोस्ट करें',
      'sell_choose_category': 'श्रेणी चुनें',
      'sell_next': 'आगे',
      'sell_category': 'श्रेणी',
      'sell_sub_category': 'उप श्रेणी',
      'sell_details': 'विवरण',
      'sell_no_categories': 'कोई श्रेणी नहीं मिली',
      'sell_retry': 'पुनः प्रयास करें',
      'sell_error_categories': 'श्रेणियां लोड करने में असमर्थ।',
      'sell_back': 'वापस',
      'sell_select_subcategory': 'उप श्रेणी चुनें',
      'sell_selected_category': 'चयनित श्रेणी: ',
      'sell_change_by_back': 'आप वापस जाकर इसे बदल सकते हैं',
      'sell_change': 'बदलें',
      'sell_no_subcategories': 'कोई उप-श्रेणियां नहीं मिलीं',
      'sell_subcategory_hint':
          'अधिक खरीदारों तक पहुंचने के लिए अपने विज्ञापन के लिए सबसे प्रासंगिक उप-श्रेणी चुनें।',
      'sell_error_subcategories': 'उप-श्रेणियां लोड करने में असमर्थ।',
      'sell_product_title': 'उत्पाद का शीर्षक',
      'sell_title_hint': 'उत्पाद का नाम दर्ज करें',
      'sell_description': 'विवरण',
      'sell_desc_hint': 'विस्तृत विवरण दर्ज करें',
      'sell_features': 'विशेषताएं (अल्पविराम से अलग करें)',
      'sell_features_hint': 'विशेषताएं',
      'sell_main_image': 'मुख्य उत्पाद छवि',
      'sell_no_file': 'कोई फ़ाइल नहीं चुनी गई',
      'sell_choose_file': 'फ़ाइल चुनें',
      'sell_gallery_images': 'गैलरी छवियां',
      'sell_max_images': 'अधिकतम 5 छवियां',
      'sell_price': 'कीमत (₹)',
      'sell_discount': 'छूट (%)',
      'sell_total_cost': 'कुल लागत (₹)',
      'sell_capacity': 'क्षमता',
      'sell_warranty': 'वारंटी',
      'sell_active_product': 'सक्रिय उत्पाद',
      'sell_save_product': 'उत्पाद सहेजें',
      'sell_select_main_image': 'कृपया मुख्य उत्पाद छवि चुनें।',
      'sell_required': 'आवश्यक',
      'sell_error_saving': 'उत्पाद सहेजते समय कुछ गलत हो गया।',
      'sell_review': 'समीक्षा',
      'sell_review_title': 'आपका आवेदन समीक्षा के अधीन है',
      'sell_review_desc':
          'हमें आपके उत्पाद का विवरण प्राप्त हो गया है। हमारी टीम जल्द ही इसकी समीक्षा करेगी।',
      'sell_go_dashboard': 'डैशबोर्ड पर जाएं',

      // Available Jobs
      'jobs_available_title': 'उपलब्ध नौकरियां',
      'jobs_no_jobs_found': 'इस भूमिका के लिए कोई नौकरी उपलब्ध नहीं है।',
      'jobs_loading': 'नौकरी के अवसर लोड हो रहे हैं...',
      'jobs_error': 'नौकरी के अवसर लोड नहीं हो सके।',
      'jobs_vacancy': 'रिक्ति',
      'jobs_vacancies': 'रिक्तियां',
      'jobs_walkin': 'वॉक-इन',
      'jobs_apply': 'आवेदन करें',
      'jobs_salary_range': 'वेतन',
      'jobs_experience': 'अनुभव',
      'jobs_applications': 'आवेदन',
      'jobs_view_details': 'विवरण देखें',
    },
  };

  String text(String key) {
    final langCode = locale.languageCode;
    final langMap = _localizedValues[langCode] ?? _localizedValues['en']!;
    return langMap[key] ?? _localizedValues['en']![key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales
      .map((e) => e.languageCode)
      .contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
