import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:rojgar/localization/app_localizations.dart';
import '../../../jobs/domain/entities/available_job_entity.dart';
import '../controllers/employer_dashboard_controller.dart';

class PostJobFormScreen extends StatefulWidget {
  const PostJobFormScreen({super.key});

  @override
  State<PostJobFormScreen> createState() => _PostJobFormScreenState();
}

class _PostJobFormScreenState extends State<PostJobFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final EmployerDashboardController controller = Get.find();

  // Color constants
  static const Color primaryBlue = Color(0xFF1400FF);
  static const Color darkText = Color(0xFF1A1A2E);
  static const Color greyText = Color(0xFF8A8FA3);
  static const Color fieldBg = Color(0xFFF7F8FF);
  static const Color borderColor = Color(0xFFD0D5F5);

  // Form Field Controllers
  final _titleCtrl = TextEditingController();
  final _vacancyCtrl = TextEditingController(text: '1');
  final _addressCtrl = TextEditingController();
  final _pincodeCtrl = TextEditingController();
  final _fixedSalaryCtrl = TextEditingController();
  final _minSalaryCtrl = TextEditingController();
  final _maxSalaryCtrl = TextEditingController();
  final _skillsCtrl = TextEditingController();
  final _descCtrl = TextEditingController();
  final _contactPersonCtrl = TextEditingController();
  final _contactPhoneCtrl = TextEditingController();
  final _contactEmailCtrl = TextEditingController();

  // Dropdown / Selection Values
  String _jobType = 'full_time';
  String _workLocationType = 'office';
  String _payType = 'fixed';
  String _educationLevel = '10th Pass';
  String _englishLevel = 'No English required';
  String _experienceLevel = 'fresher';
  String _contactPreference = 'call';
  String _stateName = 'Rajasthan';

  @override
  void dispose() {
    _titleCtrl.dispose();
    _vacancyCtrl.dispose();
    _addressCtrl.dispose();
    _pincodeCtrl.dispose();
    _fixedSalaryCtrl.dispose();
    _minSalaryCtrl.dispose();
    _maxSalaryCtrl.dispose();
    _skillsCtrl.dispose();
    _descCtrl.dispose();
    _contactPersonCtrl.dispose();
    _contactPhoneCtrl.dispose();
    _contactEmailCtrl.dispose();
    super.dispose();
  }

  void _submit() {
    if (!_formKey.currentState!.validate()) return;

    final List<String> skillsList = _skillsCtrl.text
        .split(',')
        .map((s) => s.trim())
        .where((s) => s.isNotEmpty)
        .toList();

    final newJob = AvailableJob(
      id: 0, // Generated by database
      employerId: controller.employerId.value,
      categoryId: 1, // Default general category
      roleId: 1, // Default general role
      title: _titleCtrl.text.trim(),
      jobType: _jobType,
      shifts: const ['Day Shift'],
      workLocationType: _workLocationType,
      stateName: _stateName,
      addressLine1: _addressCtrl.text.trim(),
      addressLine2: '',
      pincode: _pincodeCtrl.text.trim(),
      payType: _payType,
      fixedSalary: _payType == 'fixed' ? _fixedSalaryCtrl.text.trim() : null,
      minSalary: _payType == 'range' ? _minSalaryCtrl.text.trim() : null,
      maxSalary: _payType == 'range' ? _maxSalaryCtrl.text.trim() : null,
      perks: const ['Training provided'],
      educationLevel: _educationLevel,
      englishLevel: _englishLevel,
      experienceLevel: _experienceLevel,
      additionalRequirements: const {},
      skills: skillsList,
      languages: const ['Hindi'],
      jobDescription: _descCtrl.text.trim(),
      vacancy: int.tryParse(_vacancyCtrl.text) ?? 1,
      isWalkin: false,
      contactPreference: _contactPreference,
      contactPerson: _contactPersonCtrl.text.trim(),
      contactPhone: _contactPhoneCtrl.text.trim(),
      contactEmail: _contactEmailCtrl.text.trim(),
      viewsCount: 0,
      applicationsCount: 0,
      status: 'active',
      createdAt: DateTime.now(),
    );

    controller.postNewJob(newJob).then((_) {
      Get.back();
      Get.snackbar(
        'Success',
        'Job posted successfully!',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.green,
        colorText: Colors.white,
        margin: const EdgeInsets.all(16),
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;

    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        scrolledUnderElevation: 0,
        title: Text(
          l10n.text('employer_dashboard_post_job'),
          style: const TextStyle(color: primaryBlue, fontWeight: FontWeight.bold, fontSize: 20),
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: primaryBlue),
          onPressed: () => Get.back(),
        ),
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(1),
          child: Container(height: 1, color: const Color(0xFFEEEEEE)),
        ),
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildSectionTitle('Job Details'),
              _buildTextField(
                label: 'Job Title *',
                hint: 'e.g. Delivery Executive, Telecaller',
                controller: _titleCtrl,
                validator: (val) => val!.trim().isEmpty ? 'Please enter job title' : null,
              ),
              Row(
                children: [
                  Expanded(
                    child: _buildDropdownField(
                      label: 'Job Type *',
                      value: _jobType,
                      items: const [
                        DropdownMenuItem(value: 'full_time', child: Text('Full Time')),
                        DropdownMenuItem(value: 'part_time', child: Text('Part Time')),
                        DropdownMenuItem(value: 'contract', child: Text('Contract')),
                        DropdownMenuItem(value: 'internship', child: Text('Internship')),
                      ],
                      onChanged: (val) => setState(() => _jobType = val!),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: _buildDropdownField(
                      label: 'Work Location *',
                      value: _workLocationType,
                      items: const [
                        DropdownMenuItem(value: 'office', child: Text('Office')),
                        DropdownMenuItem(value: 'remote', child: Text('Remote')),
                        DropdownMenuItem(value: 'field', child: Text('Field')),
                        DropdownMenuItem(value: 'hybrid', child: Text('Hybrid')),
                      ],
                      onChanged: (val) => setState(() => _workLocationType = val!),
                    ),
                  ),
                ],
              ),
              _buildTextField(
                label: 'Vacancies *',
                hint: 'e.g. 5',
                controller: _vacancyCtrl,
                keyboardType: TextInputType.number,
                validator: (val) => int.tryParse(val ?? '') == null ? 'Enter valid number' : null,
              ),

              const SizedBox(height: 20),
              _buildSectionTitle('Salary & Location'),
              _buildDropdownField(
                label: 'Salary Model *',
                value: _payType,
                items: const [
                  DropdownMenuItem(value: 'fixed', child: Text('Fixed Monthly Pay')),
                  DropdownMenuItem(value: 'range', child: Text('Monthly Range (Min - Max)')),
                ],
                onChanged: (val) => setState(() => _payType = val!),
              ),
              if (_payType == 'fixed')
                _buildTextField(
                  label: 'Fixed Salary (₹) *',
                  hint: 'e.g. 15000',
                  controller: _fixedSalaryCtrl,
                  keyboardType: TextInputType.number,
                  validator: (val) => val!.trim().isEmpty ? 'Please enter salary' : null,
                )
              else
                Row(
                  children: [
                    Expanded(
                      child: _buildTextField(
                        label: 'Min Salary (₹) *',
                        hint: 'e.g. 10000',
                        controller: _minSalaryCtrl,
                        keyboardType: TextInputType.number,
                        validator: (val) => val!.trim().isEmpty ? 'Enter min' : null,
                      ),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: _buildTextField(
                        label: 'Max Salary (₹) *',
                        hint: 'e.g. 15000',
                        controller: _maxSalaryCtrl,
                        keyboardType: TextInputType.number,
                        validator: (val) => val!.trim().isEmpty ? 'Enter max' : null,
                      ),
                    ),
                  ],
                ),
              _buildTextField(
                label: 'Office Address / Hub Address *',
                hint: 'House/Shop no, Area, Locality',
                controller: _addressCtrl,
                maxLines: 2,
                validator: (val) => val!.trim().isEmpty ? 'Address is required' : null,
              ),
              Row(
                children: [
                  Expanded(
                    child: _buildDropdownField(
                      label: 'State *',
                      value: _stateName,
                      items: const [
                        DropdownMenuItem(value: 'Rajasthan', child: Text('Rajasthan')),
                        DropdownMenuItem(value: 'Maharashtra', child: Text('Maharashtra')),
                        DropdownMenuItem(value: 'Tamil Nadu', child: Text('Tamil Nadu')),
                        DropdownMenuItem(value: 'Uttar Pradesh', child: Text('Uttar Pradesh')),
                        DropdownMenuItem(value: 'Karnataka', child: Text('Karnataka')),
                      ],
                      onChanged: (val) => setState(() => _stateName = val!),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: _buildTextField(
                      label: 'Pin Code *',
                      hint: '302017',
                      controller: _pincodeCtrl,
                      keyboardType: TextInputType.number,
                      validator: (val) => val!.trim().length != 6 ? 'Must be 6 digits' : null,
                    ),
                  ),
                ],
              ),

              const SizedBox(height: 20),
              _buildSectionTitle('Candidate Requirements'),
              Row(
                children: [
                  Expanded(
                    child: _buildDropdownField(
                      label: 'Min Education *',
                      value: _educationLevel,
                      items: const [
                        DropdownMenuItem(value: '10th Pass', child: Text('10th Pass')),
                        DropdownMenuItem(value: '12th Pass', child: Text('12th Pass')),
                        DropdownMenuItem(value: 'Graduate', child: Text('Graduate')),
                        DropdownMenuItem(value: 'Post Graduate', child: Text('Post Graduate')),
                      ],
                      onChanged: (val) => setState(() => _educationLevel = val!),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: _buildDropdownField(
                      label: 'Experience Required *',
                      value: _experienceLevel,
                      items: const [
                        DropdownMenuItem(value: 'fresher', child: Text('Fresher (0 Years)')),
                        DropdownMenuItem(value: '1', child: Text('1 Year')),
                        DropdownMenuItem(value: '2', child: Text('2 Years')),
                        DropdownMenuItem(value: '3', child: Text('3 Years')),
                        DropdownMenuItem(value: '5', child: Text('5+ Years')),
                      ],
                      onChanged: (val) => setState(() => _experienceLevel = val!),
                    ),
                  ),
                ],
              ),
              _buildDropdownField(
                label: 'English Requirements *',
                value: _englishLevel,
                items: const [
                  DropdownMenuItem(value: 'No English required', child: Text('No English required')),
                  DropdownMenuItem(value: 'Basic English', child: Text('Basic English (Speak/Read)')),
                  DropdownMenuItem(value: 'Good English', child: Text('Good English (Fluent)')),
                ],
                onChanged: (val) => setState(() => _englishLevel = val!),
              ),
              _buildTextField(
                label: 'Key Skills (comma separated) *',
                hint: 'e.g. Driving License, Typing, MS Excel',
                controller: _skillsCtrl,
                validator: (val) => val!.trim().isEmpty ? 'Add at least one skill' : null,
              ),
              _buildTextField(
                label: 'Job Description',
                hint: 'Briefly describe roles, responsibilities, and benefits...',
                controller: _descCtrl,
                maxLines: 4,
              ),

              const SizedBox(height: 20),
              _buildSectionTitle('Contact Details'),
              _buildTextField(
                label: 'Contact Person Name *',
                hint: 'e.g. Raman Khanna',
                controller: _contactPersonCtrl,
                validator: (val) => val!.trim().isEmpty ? 'Required field' : null,
              ),
              _buildTextField(
                label: 'Contact Phone Number *',
                hint: '10-digit number',
                controller: _contactPhoneCtrl,
                keyboardType: TextInputType.phone,
                validator: (val) => val!.trim().length != 10 ? 'Enter valid phone' : null,
              ),
              _buildTextField(
                label: 'Contact Email Address',
                hint: 'e.g. jobs@company.com',
                controller: _contactEmailCtrl,
                keyboardType: TextInputType.emailAddress,
              ),
              _buildDropdownField(
                label: 'Candidate Contact Preference *',
                value: _contactPreference,
                items: const [
                  DropdownMenuItem(value: 'call', child: Text('Direct Phone Call')),
                  DropdownMenuItem(value: 'whatsapp', child: Text('WhatsApp Message')),
                  DropdownMenuItem(value: 'email', child: Text('Email Application')),
                ],
                onChanged: (val) => setState(() => _contactPreference = val!),
              ),

              const SizedBox(height: 32),
              SizedBox(
                width: double.infinity,
                height: 56,
                child: ElevatedButton(
                  onPressed: _submit,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: primaryBlue,
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(28)),
                    elevation: 4,
                  ),
                  child: const Text(
                    'Post Job Now',
                    style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                  ),
                ),
              ),
              const SizedBox(height: 24),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16, top: 8),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(color: primaryBlue, fontSize: 16, fontWeight: FontWeight.w800),
          ),
          const SizedBox(height: 4),
          Container(width: 40, height: 3, color: primaryBlue),
        ],
      ),
    );
  }

  Widget _buildTextField({
    required String label,
    required String hint,
    required TextEditingController controller,
    String? Function(String?)? validator,
    TextInputType keyboardType = TextInputType.text,
    int maxLines = 1,
  }) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(label, style: const TextStyle(color: darkText, fontSize: 14, fontWeight: FontWeight.w600)),
          const SizedBox(height: 6),
          Container(
            decoration: BoxDecoration(
              color: fieldBg,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: borderColor, width: 1.5),
            ),
            child: TextFormField(
              controller: controller,
              validator: validator,
              keyboardType: keyboardType,
              maxLines: maxLines,
              style: const TextStyle(color: darkText, fontSize: 15),
              decoration: InputDecoration(
                hintText: hint,
                hintStyle: const TextStyle(color: greyText, fontSize: 14),
                border: InputBorder.none,
                contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildDropdownField<T>({
    required String label,
    required T value,
    required List<DropdownMenuItem<T>> items,
    required void Function(T?) onChanged,
  }) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(label, style: const TextStyle(color: darkText, fontSize: 14, fontWeight: FontWeight.w600)),
          const SizedBox(height: 6),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            decoration: BoxDecoration(
              color: fieldBg,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: borderColor, width: 1.5),
            ),
            child: DropdownButtonHideUnderline(
              child: DropdownButton<T>(
                value: value,
                items: items,
                onChanged: onChanged,
                isExpanded: true,
                style: const TextStyle(color: darkText, fontSize: 15),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
